# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Nov 11 04:41:21 2020
# ------------------------------------------------

package:
    name: jeepney
    version: 0.5.0
source:
    fn: jeepney-0.5.0.tar.gz
    sha256: 2531d17ccfb3485d4eaee03c1a19a75f28b3ac0fbb5a1b683b77b820e5b0f509
    url: https://pypi.io/packages/source/j/jeepney/jeepney-0.5.0.tar.gz
build:
    noarch: python
    number: '0'
    script: FLIT_ROOT_INSTALL=1 flit install --deps none
    string: pyhd3eb1b0_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - brotlipy 0.7.0 py38h7b6447c_1000
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - cffi 1.14.3 py38he30daa8_0
        - chardet 3.0.4 py38_1003
        - cryptography 3.1.1 py38h1ba5d50_0
        - docutils 0.16 py38_1
        - flit 3.0.0 py_0
        - flit-core 3.0.0 py_0
        - idna 2.10 py_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py38h06a4308_0
        - pycparser 2.20 py_2
        - pyopenssl 19.1.0 py_1
        - pysocks 1.7.1 py38_0
        - python 3.8.5 h7579374_1
        - pytoml 0.1.21 py_0
        - readline 8.0 h7b6447c_0
        - requests 2.24.0 py_0
        - requests_download 0.1.2 py_1
        - setuptools 50.3.1 py38h06a4308_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - urllib3 1.25.11 py_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
test:
    imports:
        - jeepney
about:
    description: 'This is a low-level, pure Python DBus protocol client. It has

        an I/O-free core, and integration modules for different event

        loops.

        '
    dev_url: https://gitlab.com/takluyver/jeepney
    doc_url: https://jeepney.readthedocs.io/en/latest/
    home: https://gitlab.com/takluyver/jeepney
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Pure Python DBus interface
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - takluyver
