# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/scipy-1.5.2-python_3.8-blas_impl_mkl-on-linux_64, last modified Mon Aug 10 19:26:35 2020
# ------------------------------------------------

package:
    name: scipy
    version: 1.5.2
source:
    sha256: f2c055e286a9421135407d3cb3efd3f1f7ae9a465b5edc0be14ac8c5c63f6ea1
    url: https://github.com/scipy/scipy/archive/v1.5.2.tar.gz
build:
    number: '0'
    string: py38h0b6359f_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gfortran_impl_linux-64 7.3.0 hdf63c60_1
        - gfortran_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.21 py38he6710b0_0
        - intel-openmp 2019.4 243
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2019.4 243
        - mkl-devel 2019.4 243
        - mkl-include 2019.4 243
        - mkl-service 2.3.0 py38he904b0f_0
        - ncurses 6.2 he6710b0_1
        - numpy-base 1.14.6 py38hde5b4d6_4
        - numpy-devel 1.14.6 py38h4ba5984_4
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - pybind11 2.5.0 py38hfd86e86_0
        - python 3.8.5 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - six 1.15.0 py_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - blas 1.0 mkl
        - libgcc-ng >=7.3.0
        - libgfortran-ng >=7,<8.0a0
        - libstdcxx-ng >=7.3.0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
test:
    requires:
        - intel-openmp 2019.*
        - mpmath
        - pytest
        - pytest-xdist
about:
    description: 'SciPy is a Python-based ecosystem of open-source software for mathematics,

        science, and engineering.

        '
    dev_url: https://github.com/scipy/scipy
    doc_url: http://www.scipy.org/docs.html
    home: http://www.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Scientific Library for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - rgommers
