# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/harfbuzz-2.4.0-on-linux_64, last modified Sat Jun 27 20:52:55 2020
# ------------------------------------------------

package:
    name: harfbuzz
    version: 2.4.0
source:
    sha256: b470eff9dd5b596edf078596b46a1f83c179449f051a469430afc15869db336f
    url: https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-2.4.0.tar.bz2
build:
    number: '1'
    run_exports:
        - harfbuzz >=2.4.0,<3.0a0
    string: hca77d97_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.2 pl526_0
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtool 2.4.6 h7b6447c_5
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.2 h14c3975_0
        - pkg-config 0.29.2 h1bed415_8
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - cairo 1.14.12 h8948797_3
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_1
        - glib 2.65.0 h3eb4bd4_0
        - gobject-introspection 1.56.1 py38h56ee657_3
        - graphite2 1.3.14 h23475e2_0
        - icu 58.2 he6710b0_3
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libpng 1.6.37 hbc83047_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuuid 1.0.3 h1bed415_2
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.10 he19cac6_1
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pcre 8.44 he6710b0_0
        - pixman 0.40.0 h7b6447c_0
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - cairo >=1.14.12,<2.0a0
        - freetype >=2.9.1,<3.0a0
        - glib >=2.65.0,<3.0a0
        - graphite2 >=1.3.14,<2.0a0
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - libxcb >=1.13,<2.0a0
test:
    commands:
        - test -f $PREFIX/lib/libharfbuzz-icu.so
        - test -f $PREFIX/lib/libharfbuzz.so
        - test -f $PREFIX/include/harfbuzz/hb-ft.h
        - test -f $PREFIX/share/gir-1.0/HarfBuzz-0.0.gir
        - hb-view --version
about:
    description: 'HarfBuzz is a text shaping library. New Harbuzz targets various
        font

        technologies while Old HarfBuzz targets only OpenType fonts.

        '
    dev_url: https://github.com/behdad/harfbuzz
    doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
    home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
    license: MIT
    license_file: COPYING
    summary: An OpenType text shaping engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pkgw
