# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/xmltodict-0.12.0-on-linux_64, last modified Tue Mar 12 06:39:19 2019
# ------------------------------------------------

package:
    name: xmltodict
    version: 0.12.0
source:
    sha256: 50d8c638ed7ecb88d90561beedbf720c9b4e851a9fa6c47ebd64e99d166d8a21
    url: https://pypi.io/packages/source/x/xmltodict/xmltodict-0.12.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/xmltodict_1552404637225/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py27_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1b h7b6447c_1
        - pip 19.0.3 py27_0
        - python 2.7.15 h9bab390_6
        - readline 7.0 h7b6447c_5
        - setuptools 40.8.0 py27_0
        - sqlite 3.26.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.1 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - xmltodict
about:
    dev_url: https://github.com/martinblech/xmltodict
    home: https://github.com/martinblech/xmltodict
    license: MIT
    license_file: LICENSE
    summary: Makes working with XML feel like you are working with JSON
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - synapticarbors
