# This file created by conda-build 3.20.1
# ------------------------------------------------

package:
    name: libllvm10
    version: 10.0.1
source:
    patches:
        - patches/expect-fastmath-entrypoints-in-add-TLI-mappings.ll.patch
        - patches/intel-D47188-svml-VF.patch
        - patches/numba-0001-Revert-Limit-size-of-non-GlobalValue-name.patch
    sha256: c5d8e30b57cbded7128d78e5e8dad811bff97a8d471896812f57fa99ee82cdf3
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/llvm-10.0.1.src.tar.xz
build:
    activate_in_script: true
    number: 5
    run_exports:
        - libllvm10 >=10.0.1,<10.1.0a0
    string: hbcb73fb_5
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2020.7.22 0
        - ccache 3.7.9 hfe4627d_0
        - cmake 3.14.0 h52cb24c_0
        - expat 2.2.9 he6710b0_2
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - krb5 1.18.2 h173b8e3_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libcurl 7.71.1 h20c2e04_1
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.9.0 h1ba5d50_1
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - rhash 1.3.8 h1ba5d50_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f $PREFIX/lib/libLLVM-10${SHLIB_EXT}
about:
    dev_url: https://github.com/llvm-mirror/llvm
    home: http://llvm.org/
    license: Apache-2.0 WITH LLVM-exception
    license_family: Apache
    license_file: LICENSE.TXT
    summary: Development headers and libraries for LLVM
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - inducer
        - isuruf
        - jakirkham
        - mingwandroid
        - timsnyder
