# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/sphinxcontrib-jsmath-1.0.1-on-linux_canary, last modified Tue Apr 16 17:04:05 2019
# ------------------------------------------------

package:
    name: sphinxcontrib-jsmath
    version: 1.0.1
source:
    sha256: a9925e4a4587247ed2191a22df5f6970656cb8ca2bd6284309578f2153e0c4b8
    url: https://pypi.io/packages/source/s/sphinxcontrib-jsmath/sphinxcontrib-jsmath-1.0.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/sphinxcontrib-jsmath_1555449285939/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1b h7b6447c_1
        - pip 19.0.3 py37_0
        - python 3.7.3 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.0.0 py37_0
        - sqlite 3.27.2 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
test:
    imports:
        - sphinxcontrib
        - sphinxcontrib.jsmath
    requires:
        - sphinx >=2
about:
    home: http://sphinx-doc.org/
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A sphinx extension which renders display math in HTML via JavaScript
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
