# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/parso-0.7.0-on-linux_64, last modified Thu Apr 30 16:36:48 2020
# ------------------------------------------------

package:
    name: parso
    version: 0.7.0
source:
    fn: parso-0.7.0.tar.gz
    sha256: 908e9fae2144a076d72ae4e25539143d40b8e3eafbaeae03c1bfe226f4cdf12c
    url: https://pypi.io/packages/source/p/parso/parso-0.7.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/parso_1588264701071/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_1
        - python 3.6.10 hcf32534_1
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py36_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - parso
        - parso.pgen2
        - parso.python
about:
    description: 'Parso is a Python parser that supports error recovery and round-trip
        parsing for different Python versions (in multiple Python versions).

        Parso is also able to list multiple syntax errors in your python file.

        '
    dev_url: https://github.com/davidhalter/parso
    doc_url: https://parso.readthedocs.io/en/latest/
    home: https://github.com/davidhalter/parso
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: A Python Parser
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - iron0012
        - synapticarbors
