# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/lazy-object-proxy-1.4.3-python_3.8-on-linux_64, last modified Wed Nov  6 22:33:22 2019
# ------------------------------------------------

package:
    name: lazy-object-proxy
    version: 1.4.3
source:
    sha256: f3900e8a5de27447acbf900b4750b0ddfd7ec1ea7fbaf11dfa911141bc522af0
    url: https://pypi.io/packages/source/l/lazy-object-proxy/lazy-object-proxy-1.4.3.tar.gz
build:
    number: '0'
    script: /tmp/build/80754af9/lazy-object-proxy_1573080208638/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps -vv
    string: py38h7b6447c_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - setuptools_scm 3.3.3 py_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - python >=3.8,<3.9.0a0
test:
    imports:
        - lazy_object_proxy
        - lazy_object_proxy.cext
about:
    dev_url: https://github.com/ionelmc/python-lazy-object-proxy
    doc_source_url: https://github.com/ionelmc/python-lazy-object-proxy/blob/master/docs/index.rst
    doc_url: https://python-lazy-object-proxy.readthedocs.org
    home: https://github.com/ionelmc/python-lazy-object-proxy
    license: BSD-2-Clause
    license_file: LICENSE
    summary: A fast and thorough lazy object proxy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
        - ocefpaf
