# This file created by conda-build 3.20.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/llvmlite-0.34.0-python_3.8-on-linux_64, last modified Sat Sep  5 16:28:50 2020
# ------------------------------------------------

package:
    name: llvmlite
    version: 0.34.0
source:
    sha256: f03ee0d19bca8f2fe922bb424a909d05c28411983b0c2bc58b020032a0d11f63
    url: https://pypi.io/packages/source/l/llvmlite/llvmlite-0.34.0.tar.gz
build:
    number: '4'
    script_env:
        - PY_VCRUNTIME_REDIST
    string: py38h269e1b5_4
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libllvm10 10.0.1 hbcb73fb_5
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - llvm 10.0.1 h21ff451_5
        - llvm-tools 10.0.1 h4a3c616_5
        - llvmdev 10.0.1 h4a3c616_5
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libllvm10 >=10.0.1,<10.1.0a0
        - libstdcxx-ng >=7.3.0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - python -m llvmlite.tests
    imports:
        - llvmlite
        - llvmlite.binding
about:
    dev_url: https://github.com/numba/llvmlite
    doc_url: http://llvmlite.pydata.org/
    home: http://llvmlite.pydata.org
    license: BSD-2-Clause
    license_file: LICENSE
    summary: A lightweight LLVM python binding for writing JIT compilers.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - marcelotrevisani
        - mbargull
        - souravsingh
        - xhochy
