# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# C:\ci\containers\000011kkcs3\tmp\build\80754af9\aggregate\alabaster-feedstock\recipe, last modified Wed Oct 30 05:07:13 2019
# ------------------------------------------------

package:
    name: alabaster
    version: 0.7.12
source:
    sha256: a661d72d58e6ea8a57f7a86e37d86716863ee5e92788398526d58b26a4e4dc02
    url: https://pypi.io/packages/source/a/alabaster/alabaster-0.7.12.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - openssl 1.1.1d he774522_3
        - pip 19.3.1 py38_0
        - python 3.8.0 hff0d562_0
        - setuptools 41.4.0 py38_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - wheel 0.33.6 py38_0
        - wincertstore 0.2 py38_0
    run:
        - python
test:
    commands:
        - python -c "import alabaster; print(alabaster.get_path())"
    imports:
        - alabaster
about:
    description: 'Alabaster is a visually clean, responsive, and configurable Sphinx

        theme. It is sidebar-enabled and easy to install/use as a Python

        package. As of Sphinx 1.3, Alabaster is selected as the default

        theme for Sphinx.

        '
    dev_url: https://github.com/bitprophet/alabaster
    doc_url: https://anaconda.org/anaconda/alabaster
    home: http://www.sphinx-doc.org/en/stable/index.html
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Configurable, Python 2+3 compatible Sphinx theme.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - r-jain1
