# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/widgetsnbextension-3.5.1-python_3.8-on-linux_64, last modified Wed Aug 21 15:43:09 2019
# ------------------------------------------------

package:
    name: widgetsnbextension
    version: 3.5.1
source:
    sha256: 079f87d87270bce047512400efd70238820751a11d2d8cb137a5a5bdbaf255c7
    url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-3.5.1.tar.gz
build:
    number: '0'
    script: /tmp/build/80754af9/widgetsnbextension_1580237076776/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - attrs 19.3.0 py_0
        - backcall 0.1.0 py38_0
        - bleach 3.1.0 py_0
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - decorator 4.4.1 py_0
        - defusedxml 0.6.0 py_0
        - entrypoints 0.3 py38_0
        - gmp 6.1.2 h6c8ec71_1
        - importlib_metadata 1.4.0 py38_0
        - ipykernel 5.1.4 py38h39e3cac_0
        - ipython 7.11.1 py38h39e3cac_0
        - ipython_genutils 0.2.0 py38_0
        - jedi 0.16.0 py38_0
        - jinja2 2.10.3 py_0
        - jsonschema 3.2.0 py38_0
        - jupyter_client 5.3.4 py38_0
        - jupyter_core 4.6.1 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libsodium 1.0.16 h1bed415_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - markupsafe 1.1.1 py38h7b6447c_0
        - mistune 0.8.4 py38h7b6447c_1000
        - more-itertools 8.0.2 py_0
        - nbconvert 5.6.1 py38_0
        - nbformat 5.0.4 py_0
        - ncurses 6.1 he6710b0_1
        - notebook 6.0.3 py38_0
        - openssl 1.1.1d h7b6447c_3
        - pandoc 2.2.3.2 0
        - pandocfilters 1.4.2 py38_1
        - parso 0.6.0 py_0
        - pexpect 4.8.0 py38_0
        - pickleshare 0.7.5 py38_1000
        - pip 20.0.2 py38_0
        - prometheus_client 0.7.1 py_0
        - prompt_toolkit 3.0.2 py_0
        - ptyprocess 0.6.0 py38_0
        - pygments 2.5.2 py_0
        - pyrsistent 0.15.7 py38h7b6447c_0
        - python 3.8.1 h0371630_1
        - python-dateutil 2.8.1 py_0
        - pyzmq 18.1.0 py38he6710b0_0
        - readline 7.0 h7b6447c_5
        - send2trash 1.5.0 py38_0
        - setuptools 45.1.0 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - terminado 0.8.3 py38_0
        - testpath 0.4.4 py_0
        - tk 8.6.8 hbc83047_0
        - tornado 6.0.3 py38h7b6447c_0
        - traitlets 4.3.3 py38_0
        - wcwidth 0.1.7 py38_0
        - webencodings 0.5.1 py38_1
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zeromq 4.3.1 he6710b0_3
        - zipp 0.6.0 py_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - notebook >=4.4.1
        - python >=3.8,<3.9.0a0
test:
    imports:
        - widgetsnbextension
about:
    description: 'Interactive HTML widgets for Jupyter notebooks.

        '
    dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/master/widgetsnbextension
    doc_url: https://pypi.python.org/pypi/widgetsnbextension
    home: http://ipython.org
    license: BSD 3-clause
    license_family: BSD
    license_file: LICENSE
    summary: Interactive Widgets for Jupyter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - jakirkham
        - jasongrout
        - minrk
        - ocefpaf
        - pbugnion
        - pelson
        - willingc
