# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Tue Oct 20 16:54:58 2020
# ------------------------------------------------

package:
    name: freetype
    version: 2.10.4
source:
    patches:
        - 0003-Install-the-pkg-config-file-on-Windows-too.patch
    sha256: 5eab795ebb23ac77001cfb68b7d4d50b5d6c7469247b0b01b2c953269f658dac
    url: http://download.savannah.gnu.org/releases/freetype/freetype-2.10.4.tar.gz
build:
    number: '0'
    run_exports:
        - freetype >=2.10.4,<3.0a0
    string: h5ab3b9f_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libpng 1.6.37 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libpng >=1.6.37,<1.7.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - ${PREFIX}/bin/freetype-config --version
about:
    description: 'FreeType is designed to be small, efficient, highly customizable

        and portable while capable of producing high-quality output (glyph images)

        of most vector and bitmap font formats.

        '
    dev_url: http://git.savannah.gnu.org/cgit/freetype/
    doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
    doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
    home: https://www.freetype.org/
    license: GPL-2.0-only and LicenseRef-FreeType
    license_file:
        - docs/FTL.TXT
        - docs/GPLv2.TXT
    summary: A Free, High-Quality, and Portable Font Engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - msarahan
        - ocefpaf
