# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libxslt-1.1.34-on-linux_64, last modified Fri Jun 12 18:57:00 2020
# ------------------------------------------------

package:
    name: libxslt
    version: 1.1.34
source:
    fn: libxslt-1.1.34.tar.gz
    patches:
        - 0002-win-profiler-config.patch
    sha256: 98b1bd46d6792925ad2dfe9a87452ea2adebf69dcb9919ffd55bf926a7f93f7f
    url: http://xmlsoft.org/sources/libxslt-1.1.34.tar.gz
build:
    number: '0'
    run_exports:
        - libxslt >=1.1.34,<2.0a0
    string: hc22bd24_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
    host:
        - _libgcc_mutex 0.1 main
        - icu 58.2 he6710b0_3
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libxml2 2.9.10 he19cac6_1
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.3.0
        - libxml2 >=2.9.10,<2.10.0a0
test:
    commands:
        - xsltproc --version
        - conda inspect linkages -p $PREFIX libxslt
about:
    description: '"Libxslt is the XSLT C library developed for the GNOME project.

        XSLT itself is a an XML language to define transformation for XML.

        Libxslt is based on libxml2 the XML C library developed for the GNOME project.

        It also implements most of the EXSLT set of processor-portable extensions
        functions

        and some of Saxon''s evaluate and expressions extensions."

        '
    doc_source_url: https://github.com/GNOME/libxslt/tree/master/doc
    doc_url: http://xmlsoft.org/XSLT/
    home: http://xmlsoft.org/XSLT/
    license: MIT
    license_file: COPYING
    summary: The XSLT C library developed for the GNOME project
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chenghlee
        - ocefpaf
