# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/testpath-0.4.4-on-linux_64, last modified Sat Nov 16 20:42:45 2019
# ------------------------------------------------

package:
    name: testpath
    version: 0.4.4
source:
    sha256: 60e0a3261c149755f4399a1fff7d37523179a70fdc3abdf78de9fc2604aeec7e
    url: https://pypi.io/packages/source/t/testpath/testpath-0.4.4.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/testpath_1573942915834/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps --ignore-installed -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - asn1crypto 1.2.0 py37_0
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py37_0
        - cffi 1.13.2 py37h2e261b9_0
        - chardet 3.0.4 py37_1003
        - cryptography 2.8 py37h1ba5d50_0
        - docutils 0.15.2 py37_0
        - flit 1.3 py37_0
        - idna 2.8 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py37_0
        - pycparser 2.19 py37_0
        - pyopenssl 19.0.0 py37_0
        - pysocks 1.7.1 py37_0
        - python 3.7.5 h0371630_0
        - pytoml 0.1.21 py_0
        - readline 7.0 h7b6447c_5
        - requests 2.22.0 py37_0
        - requests_download 0.1.2 py37_0
        - setuptools 41.6.0 py37_0
        - six 1.13.0 py37_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - urllib3 1.24.2 py37_0
        - wheel 0.33.6 py37_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - testpath
about:
    description: 'Testpath contains functions to check things on the filesystem,

        and tools for mocking system commands and recording calls to those.

        '
    dev_url: https://github.com/jupyter/testpath
    doc_url: https://testpath.readthedocs.io
    home: https://testpath.readthedocs.io
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Testpath is a collection of utilities for Python code working with files
        and commands.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
        - takluyver
