# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Oct 21 16:30:09 2020
# ------------------------------------------------

package:
    name: bokeh
    version: 2.2.3
source:
    sha256: c4a3f97afe5f525019dd58ee8c4e3d43f53fe1b1ac264ccaae9b02c07b2abc17
    url: https://pypi.io/packages/source/b/bokeh/bokeh-2.2.3.tar.gz
build:
    entry_points:
        - bokeh = bokeh.__main__:main
    number: '0'
    script:
        - /tmp/build/80754af9/bokeh_1603297833684/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
            -m pip install . -vv
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - jinja2 >=2.7
        - numpy >=1.11.3
        - packaging >=16.8
        - pillow >=7.1.0
        - python >=3.8,<3.9.0a0
        - python-dateutil >=2.1
        - pyyaml >=3.10
        - tornado >=5.1
        - typing_extensions >=3.7.4
test:
    commands:
        - pip check
        - bokeh --help
    imports:
        - bokeh
        - bokeh.application
        - bokeh.application.handlers
        - bokeh.client
        - bokeh.command
        - bokeh.command.subcommands
        - bokeh.core
        - bokeh.core.property
        - bokeh.core.validation
        - bokeh.models
        - bokeh.models.widgets
        - bokeh.plotting
        - bokeh.protocol
        - bokeh.protocol.messages
        - bokeh.sampledata
        - bokeh.server
        - bokeh.server.views
        - bokeh.sphinxext
        - bokeh.themes
        - bokeh.util
    requires:
        - pip
about:
    description: 'Bokeh is a Python interactive visualization library that targets

        modern web browsers for presentation. Its goal is to provide elegant,

        concise  construction of novel graphics in the style of D3.js, and to

        extend this capability with high-performance interactivity over very

        large or streaming datasets. Bokeh can help anyone who would like to

        quickly and easily create interactive plots, dashboards, and data

        applications.

        '
    dev_url: http://github.com/bokeh/bokeh
    doc_url: http://bokeh.pydata.org/en/latest/docs/user_guide.html
    home: http://bokeh.pydata.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Statistical and novel interactive HTML plots for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - almarklein
        - jakirkham
        - mattpap
        - ocefpaf
        - philippjfr
