# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/jbig-feedstock/recipe, last modified Sun Sep 17 15:40:28 2017
# ------------------------------------------------

package:
    name: jbig
    version: '2.1'
source:
    git_rev: '2.1'
    git_url: https://www.cl.cam.ac.uk/~mgk25/git/jbigkit
build:
    string: hdba287a_0
requirements:
    build:
        - binutils_linux-64 2.28.1 he4fe6c7_1
        - gcc_linux-64 7.2.0 hc7b1ceb_1
    run:
        - libgcc-ng >=7.2.0
test:
    commands:
        - test -f ${PREFIX}/lib/libjbig.a
about:
    description: 'JBIG-KIT provides a portable library of compression and decompression

        functions with a documented interface that you can include very easily

        into your image or document processing software.

        '
    dev_url: https://www.cl.cam.ac.uk/~mgk25/git/jbigkit/
    doc_url: https://www.cl.cam.ac.uk/~mgk25/jbigkit/
    home: https://www.cl.cam.ac.uk/~mgk25/jbigkit
    license: GPL-2.0
    license_family: GPL
    license_file: COPYING
    summary: Implementation of the JBIG1 data compression standard
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - nehaljwani
