# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libxml2-2.9.10-on-linux_64, last modified Wed Oct 21 00:10:12 2020
# ------------------------------------------------

package:
    name: libxml2
    version: 2.9.10
source:
    patches:
        - 0002-Make-and-install-a-pkg-config-file-on-Windows.patch
        - 0004-CVE-2017-8872.patch
        - 0005-CVE-2019-20388.patch
        - 0006-CVE-2020-24977.patch
        - 0006-CVE-2020-7595.patch
    sha256: aafee193ffb8fe0c82d4afef6ef91972cbaf5feea100edc2f262750611b4be1f
    url: http://xmlsoft.org/sources/libxml2-2.9.10.tar.gz
build:
    number: '3'
    run_exports:
        - libxml2 >=2.9.10,<2.10.0a0
    string: hb55368b_3
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.2 pl526_0
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtool 2.4.6 h7b6447c_1005
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.2 h14c3975_0
        - pkg-config 0.29.2 h1bed415_8
    host:
        - _libgcc_mutex 0.1 main
        - icu 58.2 he6710b0_3
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.3.0
        - xz >=5.2.5,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - xmllint test.xml
        - conda inspect linkages -p $PREFIX libxml2
    files:
        - test.xml
about:
    description: 'Though libxml2 is written in C a variety of language

        bindings make it available in other environments.

        '
    dev_url: https://git.gnome.org/browse/libxml2/
    doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
    doc_url: http://xmlsoft.org/html/index.html
    home: http://xmlsoft.org/
    license: MIT
    license_family: MIT
    license_file: Copyright
    summary: The XML C parser and toolkit of Gnome
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chenghlee
        - gillins
        - jakirkham
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
        - scopatz
