# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/mpmath-feedstock/recipe, last modified Thu Nov  7 09:52:18 2019
# ------------------------------------------------

package:
    name: mpmath
    version: 1.1.0
source:
    fn: mpmath-1.1.0.tar.gz
    sha256: fc17abe05fbab3382b61a123c398508183406fa132e0223874578e20946499f6
    url: https://pypi.io/packages/source/m/mpmath/mpmath-1.1.0.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - mpmath
        - mpmath.calculus
        - mpmath.functions
        - mpmath.libmp
        - mpmath.matrices
        - mpmath.tests
about:
    description: 'mpmath is a free Python library for real and complex floating-point

        arithmetic with arbitrary precision.

        '
    dev_url: https://github.com/fredrik-johansson/mpmath
    doc_source_url: https://github.com/fredrik-johansson/mpmath/blob/master/doc/source/index.txt
    doc_url: http://mpmath.org/doc/current/
    home: http://mpmath.org
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Python library for arbitrary-precision floating-point arithmetic
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - msarahan
        - ocefpaf
