# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libarchive-3.4.2-on-linux_64, last modified Sat Apr 18 08:54:45 2020
# ------------------------------------------------

package:
    name: libarchive
    version: 3.4.2
source:
    patches:
        - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
        - patches/0002-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
        - patches/0003-VC9-compatibility-define-BCRYPT_SUCCESS.patch
        - patches/0004-VC9-compatibility-openssl-define-inline-as-__inline.patch
        - patches/0005-VC9-compatibility-Ignore-some-warnings.patch
        - patches/0006-C99-compatibility-Remove-the-limited-amount-of-C99.patch
        - patches/0007-CMake-Force-Multi-threaded-DLL-runtime.patch
    sha256: b60d58d12632ecf1e8fad7316dc82c6b9738a35625746b47ecdcaf4aed176176
    url: https://github.com/libarchive/libarchive/releases/download/v3.4.2/libarchive-3.4.2.tar.gz
build:
    number: '0'
    run_exports:
        - libarchive >=3.4.2,<3.5.0a0
    string: h62408e4_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.1 pl526_0
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtool 2.4.6 h7b6447c_5
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.2 h14c3975_0
        - pkg-config 0.29.2 h1bed415_8
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2020.1.1 0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libxml2 2.9.9 hea5a465_1
        - lz4-c 1.9.2 he6710b0_0
        - openssl 1.1.1f h7b6447c_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.4.4 h0b5b093_3
    run:
        - bzip2 >=1.0.8,<2.0a0
        - libgcc-ng >=7.3.0
        - libxml2 >=2.9.9,<2.10.0a0
        - lz4-c >=1.9.2,<1.10.0a0
        - openssl >=1.1.1f,<1.1.2a
        - xz >=5.2.5,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zstd >=1.4.4,<1.4.5.0a0
test:
    commands:
        - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
        - test -f "${PREFIX}/include/archive.h"
        - test -f "${PREFIX}/include/archive_entry.h"
        - test -f "${PREFIX}/lib/libarchive.a"
        - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"
        - bsdcat --version
        - bsdcpio --version
        - bsdtar --version
        - pushd test-archives
        - bsdtar -vxf hello_world.xar 2>&1 | rg "x hello_world"
        - bsdtar -vxf archive.7z 2>&1 | rg "x 7zip-archive"
        - bsdtar -vxf hello_world.tar.zst 2>&1 | rg "greets"
        - popd
    files:
        - test-archives
    requires:
        - ripgrep
about:
    home: http://www.libarchive.org/
    license: BSD-2-Clause
    license_family: BSD
    license_file: COPYING
    summary: Multi-format archive and compression library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
