# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/jedi-0.17.1-python_3.8-on-linux_64, last modified Mon Jun 22 16:02:56 2020
# ------------------------------------------------

package:
    name: jedi
    version: 0.17.1
source:
    sha256: 807d5d4f96711a2bcfdd5dfa3b1ae6d09aa53832b182090b222b5efb81f52f63
    url: https://pypi.io/packages/source/j/jedi/jedi-0.17.1.tar.gz
build:
    number: '0'
    script: /tmp/build/80754af9/jedi_1592841866100/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.2 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py38_1
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.0 py38_0
        - sqlite 3.32.2 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - parso >=0.7.0,<0.8.0
        - python >=3.8,<3.9.0a0
test:
    imports:
        - jedi
        - jedi.api
        - jedi.common
        - jedi.inference
        - jedi.inference.compiled
        - jedi.inference.compiled.subprocess
        - jedi.inference.gradual
        - jedi.inference.value
        - jedi.plugins
about:
    description: 'Jedi is a static analysis tool for Python that can be used in IDEs/editors.

        Its historic focus is autocompletion, but does static analysis for now as

        well. Jedi is fast and is very well tested. It understands Python on a

        deeper level than all other static analysis frameworks for Python.

        '
    dev_url: https://github.com/davidhalter/jedi/
    doc_source_url: https://github.com/davidhalter/jedi/blob/master/docs/index.rst
    doc_url: http://jedi.readthedocs.io/en/latest/
    home: https://github.com/davidhalter/jedi/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: An autocompletion tool for Python that can be used for text editors.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - asmeurer
        - goanpeca
        - nehaljwani
        - ocefpaf
