# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/backports.functools_lru_cache-1.6.1-on-linux_64, last modified Wed Nov 20 17:46:33 2019
# ------------------------------------------------

package:
    name: backports.functools_lru_cache
    version: 1.6.1
source:
    sha256: 8fde5f188da2d593bd5bc0be98d9abc46c95bb8a9dde93429570192ee6cc2d4a
    url: https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-1.6.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/backports.functools_lru_cache_1574272370033/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - backports 1.0 py_2
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py27_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py27_0
        - python 2.7.17 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py27_0
        - setuptools_scm 3.3.3 py_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - backports
        - python
        - setuptools
test:
    imports:
        - backports.functools_lru_cache
about:
    dev_url: https://github.com/jaraco/backports.functools_lru_cache
    doc_url: https://pypi.python.org/pypi/backports.functools_lru_cache
    home: https://github.com/jaraco/backports.functools_lru_cache
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Backport of functools.lru_cache from Python 3.3 as published at ActiveState.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mariusvniekerk
        - stuertz
