# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pluggy-0.13.1-python_3.8-on-linux_64, last modified Mon Nov 25 16:23:47 2019
# ------------------------------------------------

package:
    name: pluggy
    version: 0.13.1
source:
    fn: pluggy-0.13.1.tar.gz
    sha256: 15b2acde666561e1298d71b523007ed7364de07029219b604cf808bfa1c765b0
    url: https://pypi.io/packages/source/p/pluggy/pluggy-0.13.1.tar.gz
build:
    number: '0'
    script: python -m pip install . --no-deps --ignore-installed
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - setuptools_scm 3.3.3 py_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - pluggy
about:
    dev_url: https://github.com/pytest-dev/pluggy/
    doc_url: https://pluggy.readthedocs.io/en/latest/
    home: https://github.com/pytest-dev/pluggy
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Plugin registration and hook calling for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohnGreeley
        - nicoddemus
