# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pixman-0.40.0-on-linux_64, last modified Tue Jun 23 14:54:34 2020
# ------------------------------------------------

package:
    name: pixman
    version: 0.40.0
source:
    sha256: 6d200dec3740d9ec4ec8d1180e25779c00bc749f94278c8b9021f5534db223fc
    url: http://cairographics.org/releases/pixman-0.40.0.tar.gz
build:
    number: '0'
    run_exports:
        - pixman >=0.40.0,<1.0a0
    string: h7b6447c_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
        - pkg-config 0.29.2 h1bed415_8
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - test -f ${PREFIX}/lib/libpixman-1.a
about:
    description: 'Pixman is a low-level software library for pixel manipulation, providing

        features such as image compositing and trapezoid rasterization.

        '
    dev_url: https://cgit.freedesktop.org/pixman/
    home: http://www.pixman.org/
    license: MIT
    license_file: COPYING
    summary: A low-level software library for pixel manipulation.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - ocefpaf
