# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zope.event-4.5.0-python_3.8-on-linux_64, last modified Wed Oct 14 12:49:56 2020
# ------------------------------------------------

package:
    name: zope.event
    version: 4.5.0
source:
    fn: zope.event-4.5.0.tar.gz
    sha256: 5e76517f5b9b119acf37ca8819781db6c16ea433f7e2062c4afc2b6fbedb1330
    url: https://pypi.io/packages/source/z/zope.event/zope.event-4.5.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
        - setuptools
test:
    imports:
        - zope
        - zope.event
about:
    description: 'This package provides a simple event system on which application-specific

        event systems can be built. For example, a type-based event dispatching

        system that builds on zope.interface can be found in zope.component. A

        simpler system is distributed with this package and is described in

        Class-based event handlers.

        '
    dev_url: http://github.com/zopefoundation/zope.event
    doc_url: http://zopeevent.readthedocs.io/en/latest/
    home: http://www.zope.org/en/latest/
    license: Zope Public License
    license_family: OTHER
    summary: Very basic event publishing system
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
