# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Nov 11 03:48:11 2020
# ------------------------------------------------

package:
    name: distributed
    version: 2.30.1
source:
    sha256: 1421d3b84a0885aeb2c4bdc9e8896729c0f053a9375596c9de8864e055e2ac8e
    url: https://pypi.io/packages/source/d/distributed/distributed-2.30.1.tar.gz
build:
    entry_points:
        - dask-scheduler=distributed.cli.dask_scheduler:go
        - dask-ssh=distributed.cli.dask_ssh:go
        - dask-worker=distributed.cli.dask_worker:go
    number: '0'
    script: /tmp/build/80754af9/distributed_1605066520644/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38h06a4308_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py38h06a4308_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.1 py38h06a4308_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - click >=6.6
        - cloudpickle >=1.5.0
        - cytoolz >=0.8.2
        - dask-core >=2.9.0
        - msgpack-python >=0.6.0
        - psutil >=5.0
        - python >=3.8,<3.9.0a0
        - pyyaml
        - setuptools
        - sortedcontainers !=2.0.0,!=2.0.1
        - tblib >=1.6.0
        - toolz >=0.8.2
        - tornado >=6.0.3
        - zict >=0.1.3
    run_constrained:
        - openssl !=1.1.1e
test:
    commands:
        - dask-scheduler --help
        - dask-ssh --help
        - dask-worker --help
    imports:
        - distributed
        - distributed.cli
        - distributed.comm
        - distributed.deploy
        - distributed.diagnostics
        - distributed.protocol
about:
    description: 'Distributed is a lightweight library for distributed computing in
        Python.

        It extends both the concurrent.futures and dask APIs to moderate sized

        clusters.

        '
    dev_url: https://github.com/dask/distributed
    doc_source_url: https://github.com/dask/distributed/blob/master/docs/source/index.rst
    doc_url: https://distributed.dask.org
    home: http://distributed.readthedocs.io/en/latest/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Distributed computing with Dask
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jcrist
        - jrbourbeau
        - marcelotrevisani
        - martindurant
        - mrocklin
        - ogrisel
        - tomaugspurger
