# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/ply-feedstock/recipe, last modified Wed Nov  6 11:41:36 2019
# ------------------------------------------------

package:
    name: ply
    version: '3.11'
source:
    fn: ply-3.11.tar.gz
    sha256: 928c5642612f4710b168d3c49c25f6ece2913a5e8d1c5e37fde5d6162fec3fd2
    url: https://github.com/dabeaz/ply/archive/3.11.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - ply.lex
        - ply.yacc
about:
    description: 'PLY is a pure-Python implementation of the popular compiler construction

        tools lex and yacc.  The main goal of PLY is to stay fairly faithful to the
        way

        in which traditional lex/yacc tools work.

        '
    dev_url: https://github.com/dabeaz/ply
    doc_source_url: https://github.com/dabeaz/ply/blob/master/doc/internal.htmls
    doc_url: http://www.dabeaz.com/ply/index.html
    home: http://www.dabeaz.com/ply/index.html
    license: BSD 3-clause
    license_family: BSD
    license_file: README.md
    summary: Python Lex-Yacc
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - scopatz
        - synapticarbors
