# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri Oct  9 19:41:07 2020
# ------------------------------------------------

package:
    name: patchelf
    version: '0.12'
source:
    patches:
        - 0001-build-id.patch
        - 0002-remove-broken-test-r-path.patch
    sha256: 3dca33fb862213b3541350e1da262249959595903f559eae0fbc68966e9c3f56
    url: https://github.com/NixOS/patchelf/archive/0.12.tar.gz
build:
    binary_relocation: false
    number: '0'
    string: he6710b0_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.2 pl526_0
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.2 h14c3975_0
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - bash -c '[[ "$(patchelf --version)" =~ "patchelf 0.12".* ]]'
about:
    description: 'PatchELF is a small utility to modify the dynamic linker and RPATH
        of ELF

        executables.

        '
    dev_url: https://github.com/NixOS/patchelf
    doc_url: http://nixos.org/patchelf.html
    home: http://nixos.org/patchelf.html
    license: GPL-3.0-or-later
    license_file: COPYING
    summary: A small utility to modify the dynamic linker and RPATH of ELF executables.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mjuric
