# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/lcms2-2.11-on-linux_64, last modified Fri Jun 26 18:40:34 2020
# ------------------------------------------------

package:
    name: lcms2
    version: '2.11'
source:
    sha256: dc49b9c8e4d7cdff376040571a722902b682a795bf92985a85b48854c270772e
    url: https://ayera.dl.sourceforge.net/project/lcms/lcms/2.11/lcms2-2.11.tar.gz
build:
    number: '0'
    run_exports:
        - lcms2 >=2.11,<3.0a0
    string: h396b838_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
    host:
        - _libgcc_mutex 0.1 main
        - jpeg 9b h024ee3a_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtiff 4.1.0 h2733197_1
        - lz4-c 1.9.2 he6710b0_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.4.4 h0b5b093_3
    run:
        - jpeg >=9b,<10a
        - libgcc-ng >=7.3.0
        - libtiff >=4.1.0,<5.0a0
test:
    commands:
        - test -f ${PREFIX}/include/lcms2.h
        - test -f ${PREFIX}/lib/liblcms2.a
        - test -f ${PREFIX}/lib/liblcms2${SHLIB_EXT}
        - jpgicc
        - tificc
        - linkicc
        - transicc
        - psicc
about:
    home: http://www.littlecms.com/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: Open Source Color Management Engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hmaarrfk
        - isuruf
