# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libspatialindex-1.9.3-on-linux_64, last modified Wed Nov  6 17:23:39 2019
# ------------------------------------------------

package:
    name: libspatialindex
    version: 1.9.3
source:
    sha256: 7b44340a3edc55c11abfc453bb60f148b29f569cef9e1148583e76132e9c7379
    url: https://github.com/libspatialindex/libspatialindex/archive/1.9.3.tar.gz
build:
    number: '0'
    run_exports:
        - libspatialindex >=1.9.3,<1.9.4.0a0
    string: he6710b0_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2019.10.16 0
        - cmake 3.14.0 h52cb24c_0
        - expat 2.2.6 he6710b0_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - krb5 1.16.1 h173b8e3_7
        - libcurl 7.65.3 h20c2e04_0
        - libedit 3.1.20181209 hc058e9b_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.8.2 h1ba5d50_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - rhash 1.3.8 h1ba5d50_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - test -f ${PREFIX}/lib/libspatialindex_c${SHLIB_EXT}
about:
    home: http://libspatialindex.github.io
    license: MIT
    license_file: COPYING
    summary: Extensible framework for robust spatial indexing
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
