# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/xlwt-feedstock/recipe, last modified Thu Nov 14 11:11:37 2019
# ------------------------------------------------

package:
    name: xlwt
    version: 1.3.0
source:
    fn: xlwt-1.3.0.tar.gz
    sha256: c59912717a9b28f1a3c2a98fd60741014b06b043936dcecbc113eaaada156c88
    url: https://pypi.io/packages/source/x/xlwt/xlwt-1.3.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - xlwt
about:
    description: 'Xlwt is a library for developers to use to generate spreadsheet
        files

        compatible with Microsoft Excel versions 95 to 2003.

        '
    dev_url: https://github.com/python-excel/xlwt
    doc_source_url: https://github.com/python-excel/xlwt/blob/master/docs/index.rst
    doc_url: http://xlwt.readthedocs.org/en/latest/
    home: http://www.python-excel.org/
    license: BSD
    license_family: BSD
    license_file: docs/licenses.rst
    summary: Writing data and formatting information to Excel files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
