# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/simplegeneric-feedstock/recipe, last modified Fri Nov  8 08:03:35 2019
# ------------------------------------------------

package:
    name: simplegeneric
    version: 0.8.1
source:
    fn: simplegeneric-0.8.1.zip
    md5: f9c1fab00fd981be588fc32759f474e3
    url: https://pypi.python.org/packages/source/s/simplegeneric/simplegeneric-0.8.1.zip
build:
    number: '2'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py38_2
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - simplegeneric
about:
    description: 'The simplegeneric module lets you define simple single-dispatch
        generic

        functions, akin to Python''s built-in generic functions like len(), iter()

        and so on. However, instead of using specially-named methods, these

        generic functions use simple lookup tables, akin to those used by e.g.

        pickle.dump() and other generic functions found in the Python standard

        library.

        '
    doc_url: https://pypi.python.org/pypi/simplegeneric
    home: http://cheeseshop.python.org/pypi/simplegeneric
    license: Zope Public
    summary: Simple generic functions (similar to Python's own len(), pickle.dump(),
        etc.)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - msarahan
        - pelson
