# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/fastcache-feedstock/recipe, last modified Mon Nov  4 15:11:05 2019
# ------------------------------------------------

package:
    name: fastcache
    version: 1.1.0
source:
    sha256: 6de1b16e70335b7bde266707eb401a3aaec220fb66c5d13b02abf0eab8be782b
    url: https://pypi.io/packages/source/f/fastcache/fastcache-1.1.0.tar.gz
build:
    number: '0'
    script: /tmp/build/80754af9/fastcache_1572880580104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py38h7b6447c_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - python -c "import fastcache; fastcache.test()"
    imports:
        - fastcache
        - fastcache._lrucache
    requires:
        - pytest
about:
    description: 'fastcache provides speedup of 10-30x over standard library.

        It passes test suite from standard library for lru_cache.

        '
    dev_url: https://github.com/pbrady/fastcache
    doc_source_url: https://github.com/pbrady/fastcache/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/fastcache/1.0.2
    home: https://github.com/pbrady/fastcache
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: C implementation of Python 3 lru_cache
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - synapticarbors
