# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/numba-0.51.2-python_3.8-on-linux_64, last modified Fri Sep 11 17:45:23 2020
# ------------------------------------------------

package:
    name: numba
    version: 0.51.2
source:
    sha256: c3385ddea40bcf2edfe405844ef9df97e23e5b8b7f635883a5e987f519e6441b
    url: https://github.com/numba/numba/archive/0.51.2.tar.gz
build:
    entry_points:
        - numba = numba.misc.numba_entry:main
        - pycc = numba.pycc:main
    number: '1'
    script:
        - /tmp/build/80754af9/numba_1600100669015/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
            -m pip install . --no-deps --ignore-installed -vvv
    string: py38h0573a6f_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - intel-openmp 2020.2 254
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libllvm10 10.0.1 hbcb73fb_5
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - llvmlite 0.34.0 py38h269e1b5_4
        - mkl 2020.2 256
        - mkl-service 2.3.0 py38he904b0f_0
        - mkl_fft 1.1.0 py38h23d657b_0
        - mkl_random 1.1.1 py38h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - numpy 1.14.6 py38h056ac22_4
        - numpy-base 1.14.6 py38hde5b4d6_4
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - six 1.15.0 py_0
        - sqlite 3.33.0 h62c20be_0
        - tbb 2020.2 hfd86e86_0
        - tbb-devel 2020.2 hfd86e86_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - llvmlite >=0.34.0,<0.35
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
        - setuptools
        - tbb >=2020.2
    run_constrained:
        - tbb >=2019.5
test:
    imports:
        - numba
        - numba.core.annotations
        - numba.core.datamodel
        - numba.core.rewrites
        - numba.core.runtime
        - numba.core.typeconv
        - numba.core.typing
        - numba.core.unsafe
        - numba.cuda
        - numba.cuda.cudadrv
        - numba.cuda.kernels
        - numba.cuda.simulator
        - numba.cuda.simulator.cudadrv
        - numba.cuda.tests
        - numba.cuda.tests.cudadrv
        - numba.cuda.tests.cudadrv.data
        - numba.cuda.tests.cudapy
        - numba.cuda.tests.cudasim
        - numba.cuda.tests.nocuda
        - numba.experimental.jitclass
        - numba.np.ufunc
        - numba.pycc
        - numba.roc.servicelib
        - numba.scripts
        - numba.testing
        - numba.tests
        - numba.tests.npyufunc
    requires:
        - cffi
        - gcc_linux-64 7.3.0.*
        - gxx_linux-64 7.3.0.*
        - ipython
        - jinja2
        - numpy >=1.15,<1.19
        - scipy
        - setuptools
        - tbb >=2018.0.5
about:
    description: 'Numba is an Open Source NumPy-aware optimizing compiler for Python

        sponsored by Anaconda, Inc. It uses the remarkable LLVM compiler

        infrastructure to compile Python syntax to machine code."

        '
    dev_url: https://github.com/numba/numba
    doc_url: http://numba.pydata.org/
    home: http://numba.github.com
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: NumPy aware dynamic Python compiler using LLVM
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - henryiii
        - jakirkham
        - marcelotrevisani
        - mbargull
        - souravsingh
        - step21
