# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/07c74cd7-09e8-4879-4f6d-e829ec12ca35/volume/aggregate/async_generator-feedstock/recipe, last modified Wed Oct 30 07:09:22 2019
# ------------------------------------------------

package:
    name: async_generator
    version: '1.10'
source:
    sha256: 6ebb3d106c12920aaae42ccb6f787ef5eefdcdd166ea3d628fa8476abe712144
    url: https://pypi.io/packages/source/a/async_generator/async_generator-1.10.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h359304d_0
        - readline 7.0 h1de35cc_5
        - setuptools 41.4.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >2.7
test:
    imports:
        - async_generator
        - async_generator._tests
about:
    description: Python 3.6 added async generators, Python 3.7 adds some more tools
        to make them usable, like contextlib.asynccontextmanager. This library gives
        you all that back to Python 3.5.
    dev_url: https://github.com/python-trio/async_generator
    home: https://github.com/python-trio/async_generator
    license: MIT
    license_family: MIT
    summary: Async generators and context managers for Python 3.5+
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nicoddemus
