# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/backports.weakref-1.0.post1-on-linux_canary, last modified Wed Jun 12 23:37:33 2019
# ------------------------------------------------

package:
    name: backports.weakref
    version: 1.0.post1
source:
    fn: backports.weakref-1.0.post1.tar.gz
    sha256: bc4170a29915f8b22c9e7c4939701859650f2eb84184aee80da329ac0b9825c2
    url: https://pypi.io/packages/source/b/backports.weakref/backports.weakref-1.0.post1.tar.gz
build:
    noarch: python
    number: '1'
    script: /tmp/build/80754af9/backports.weakref_1560422161500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        setup.py install --single-version-externally-managed --record record.txt
    string: py_1
requirements:
    host:
        - backports 1.0 py_2
        - ca-certificates 2019.5.15 0
        - certifi 2019.3.9 py27_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1c h7b6447c_1
        - python 2.7.16 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.0.1 py27_0
        - setuptools_scm 3.3.3 py_0
        - sqlite 3.28.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - backports
        - python
test:
    imports:
        - backports.weakref
about:
    description: 'This package provides backports of new features in Python''s weakref

        module under the backports namespace.

        '
    dev_url: https://github.com/pjdelport/backports.weakref
    home: https://github.com/pjdelport/backports.weakref
    license: Python-2.0
    license_family: PSF
    summary: Backport of new features in Python's weakref module
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - adrianchia
