# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/rtree-0.9.4-python_3.8-on-linux_64, last modified Sun May  3 23:30:29 2020
# ------------------------------------------------

package:
    name: rtree
    version: 0.9.4
source:
    sha256: cae327e2c03b3da4ea40d0fdf68f3e55fe9f302c56b9f31e1bfeb36dbea73f44
    url: https://pypi.io/packages/source/R/Rtree/Rtree-0.9.4.tar.gz
build:
    number: '1'
    script: /tmp/build/80754af9/rtree_1588548847808/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps -vv
    string: py38_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libspatialindex 1.9.3 he6710b0_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py38_1
        - python 3.8.2 hcf32534_0
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py38_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libspatialindex >=1.9.3,<1.9.4.0a0
        - python >=3.8,<3.9.0a0
test:
    imports:
        - rtree
about:
    home: http://toblerity.github.com/rtree/
    license: MIT
    license_file: LICENSE.txt
    summary: R-Tree spatial index for Python GIS
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - hobu
        - ocefpaf
