# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/fribidi-1.0.10-on-linux_canary, last modified Mon Aug 17 16:58:00 2020
# ------------------------------------------------

package:
    name: fribidi
    version: 1.0.10
source:
    patches:
        - meson-rpaths.patch
    sha256: 7f1c687c7831499bcacae5e8675945a39bacbad16ecaa945e9454a32df653c01
    url: https://github.com/fribidi/fribidi/releases/download/v1.0.10/fribidi-1.0.10.tar.xz
build:
    number: '0'
    run_exports:
        - fribidi >=1.0.10,<2.0a0
    string: h7b6447c_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - meson 0.55.0 py_0
        - ncurses 6.2 he6710b0_1
        - ninja 1.10.0 py38hfd86e86_0
        - openssl 1.1.1g h7b6447c_0
        - python 3.8.5 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - fribidi -h
about:
    description: 'One of the missing links stopping the penetration of free software
        in Middle

        East is the lack of support for the Arabic and Hebrew alphabets. In order
        to

        have proper Arabic and Hebrew support, the bidi algorithm needs to be

        implemented. It is our hope that this library will stimulate more free

        software in the Middle Eastern countries.

        '
    dev_url: https://github.com/fribidi/fribidi
    doc_url: https://github.com/fribidi/fribidi
    home: https://github.com/fribidi/fribidi
    license: LGPL-2.1
    license_file: COPYING
    summary: The Free Implementation of the Unicode Bidirectional Algorithm.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mariusvniekerk
        - msarahan
