# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/patsy-feedstock/recipe, last modified Thu Nov 21 16:24:18 2019
# ------------------------------------------------

package:
    name: patsy
    version: 0.5.1
source:
    sha256: f115cec4201e1465cd58b9866b0b0e7b941caafec129869057405bfe5b5e3991
    url: https://pypi.io/packages/source/p/patsy/patsy-0.5.1.tar.gz
build:
    number: '0'
    script:
        - python setup.py install --single-version-externally-managed --record=record.txt
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - numpy >=1.4.0
        - python >=3.8,<3.9.0a0
        - scipy
        - six
test:
    imports:
        - patsy
about:
    description: 'Patsy is a Python library for describing statistical models (especially

        linear models, or models that have a linear component) and building design

        matrices.

        '
    dev_url: https://github.com/pydata/patsy
    doc_source_url: https://github.com/pydata/patsy/blob/master/doc/index.rst
    doc_url: http://patsy.readthedocs.org/en/latest/
    home: https://github.com/pydata/patsy
    license: BSD-2-Clause, PSF2
    license_family: BSD
    license_file: LICENSE.txt
    summary: Describing statistical models in Python using symbolic formulas
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - croth1
