# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Tue Oct 27 18:09:47 2020
# ------------------------------------------------

package:
    name: pillow
    version: 8.0.1
source:
    sha256: 11c5c6e9b02c9dac08af04f093eb5a2f84857df70a7d4a6a6ad461aca803fb9e
    url: https://pypi.io/packages/source/P/Pillow/Pillow-8.0.1.tar.gz
build:
    ignore_run_exports:
        - jpeg
        - tk
    number: '0'
    string: py38he98fc37_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py38_0
        - freetype 2.10.4 h5ab3b9f_0
        - jpeg 9b h024ee3a_2
        - lcms2 2.11 h396b838_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libpng 1.6.37 hbc83047_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtiff 4.1.0 h2733197_1
        - lz4-c 1.9.2 heb0550a_3
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.4.5 h9ceee32_0
    run:
        - freetype >=2.10.4,<3.0a0
        - jpeg
        - lcms2 >=2.11,<3.0a0
        - libgcc-ng >=7.3.0
        - libtiff >=4.1.0,<5.0a0
        - olefile
        - python >=3.8,<3.9.0a0
        - tk
        - zlib >=1.2.11,<1.3.0a0
test:
    imports:
        - PIL
        - PIL.Image
        - PIL.ImageCms
        - PIL._imaging
        - PIL._imagingft
        - PIL._imagingmath
        - PIL._imagingmorph
        - PIL._imagingtk
about:
    description: 'Pillow is the friendly PIL fork. PIL is the Python Imaging Library,

        adds image processing capabilities to your Python interpreter.

        '
    dev_url: https://github.com/python-pillow/Pillow
    doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
    doc_url: http://pillow.readthedocs.io/en/4.2.x/
    home: https://pillow.readthedocs.io
    license: LicenseRef-PIL
    license_file: LICENSE
    summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - patricksnape
        - pelson
