# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/msgpack-python-1.0.0-python_3.8-on-linux_64, last modified Tue Mar 24 19:32:39 2020
# ------------------------------------------------

package:
    name: msgpack-python
    version: 1.0.0
source:
    sha256: 9534d5cc480d4aff720233411a1f765be90885750b07df772380b34c10ecb5c0
    url: https://pypi.io/packages/source/m/msgpack/msgpack-1.0.0.tar.gz
build:
    number: '1'
    script: /tmp/build/80754af9/msgpack-python_1585078525372/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . -vv
    string: py38hfd86e86_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_1
        - cython 0.29.15 py38he6710b0_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1e h7b6447c_0
        - pip 20.0.2 py38_1
        - python 3.8.1 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 46.1.1 py38_0
        - sqlite 3.31.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - python >=3.8,<3.9.0a0
test:
    imports:
        - msgpack
about:
    description: 'MessagePack lets you exchange data among multiple languages like
        JSON.  But

        it is faster and smaller. Small integers are encoded into a single byte and

        typical short strings require only one extra byte in addition to the

        strings themselves.

        '
    dev_url: https://github.com/msgpack/msgpack
    doc_source_url: https://github.com/msgpack/msgpack-python/blob/master/docs/index.rst
    doc_url: http://msgpack-python.readthedocs.io/
    home: http://msgpack.org/
    license: Apache-2.0
    license_family: Apache
    license_file: COPYING
    summary: MessagePack (de)serializer
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - carlodri
        - jakirkham
        - ocefpaf
        - pmlandwehr
