# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/watchdog-0.10.3-python_3.8-on-linux_64, last modified Mon Jun 29 16:13:30 2020
# ------------------------------------------------

package:
    name: watchdog
    version: 0.10.3
source:
    fn: watchdog-0.10.3.tar.gz
    sha256: 4214e1379d128b0588021880ccaf40317ee156d4603ac388b9adcf29165e0c04
    url: https://pypi.io/packages/source/w/watchdog/watchdog-0.10.3.tar.gz
build:
    entry_points:
        - watchmedo = watchdog.watchmedo:main
    number: '0'
    script: /tmp/build/80754af9/watchdog_1593447344699/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps -vv
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.1.1 py38_1
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - argh >=0.24.1
        - pathtools >=0.1.1
        - python >=3.8,<3.9.0a0
        - pyyaml >=3.10
test:
    commands:
        - python -m pip check
        - watchmedo --help
    imports:
        - watchdog
        - watchdog.observers
        - watchdog.tricks
        - watchdog.utils
    requires:
        - pip
about:
    doc_url: http://pythonhosted.org/watchdog
    home: http://github.com/gorakhargosh/watchdog
    license: Apache 2.0
    license_file: LICENSE
    summary: Filesystem events monitoring
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - andfoy
        - ccordoba12
        - goanpeca
        - rlaverde
