# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/docutils-0.16-python_3.8-on-linux_64, last modified Wed Jun 10 11:34:37 2020
# ------------------------------------------------

package:
    name: docutils
    version: '0.16'
source:
    sha256: c2de3a60e9e7d07be26b7f2b00ca0309c207e06c100f9cc2a94931fc75a478fc
    url: https://pypi.io/packages/source/d/docutils/docutils-0.16.tar.gz
build:
    number: '1'
    script: /tmp/build/80754af9/docutils_1591789123944/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps -vv
    string: py38_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py38_3
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 47.1.1 py38_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - docutils
        - docutils.languages
        - docutils.parsers
        - docutils.parsers.rst
        - docutils.parsers.rst.directives
        - docutils.parsers.rst.languages
        - docutils.readers
        - docutils.transforms
        - docutils.utils
        - docutils.utils.math
        - docutils.writers
        - docutils.writers.html4css1
        - docutils.writers.html5_polyglot
        - docutils.writers.latex2e
        - docutils.writers.odf_odt
        - docutils.writers.pep_html
        - docutils.writers.s5_html
        - docutils.writers.xetex
about:
    description: 'Docutils is an open-source text processing system for processing
        plaintext

        documentation into useful formats, such as HTML, LaTeX, man-pages, open-

        document, or XML.

        '
    dev_url: http://svn.code.sf.net/p/docutils/code
    doc_source_url: https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docs/index.txt
    doc_url: http://docutils.sourceforge.net/docs/index.html
    home: http://docutils.sourceforge.net/
    license: Public Domain Dedictation and BSD 2-Clause and PSF 2.1.1 and GPL 3.0
    license_file: COPYING.txt
    summary: Docutils -- Python Documentation Utilities
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
        - ocefpaf
        - pmlandwehr
