# This file created by conda-build 3.18.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/glob2-0.7-on-linux_64, last modified Tue Jul  2 16:42:21 2019
# ------------------------------------------------

package:
    name: glob2
    version: '0.7'
source:
    fn: glob2-0.7.tar.gz
    sha256: 85c3dbd07c8aa26d63d7aacee34fa86e9a91a3873bc30bf62ec46e531f92ab8c
    url: https://pypi.io/packages/source/g/glob2/glob2-0.7.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed . --verbose
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.5.15 0
        - certifi 2019.6.16 py27_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1c h7b6447c_1
        - pip 19.1.1 py27_0
        - python 2.7.16 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.0.1 py27_0
        - sqlite 3.28.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.4 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - glob2
about:
    description: 'The glob module finds all the pathnames matching a specified pattern
        according to the rules

        used by the Unix shell, although results are returned in arbitrary order.
        No tilde expansion

        is done, but *, ?, and character ranges expressed with [] will be correctly
        matched.

        '
    dev_url: https://github.com/miracle2k/python-glob2
    doc_url: https://docs.python.org/3/library/glob.html
    home: https://github.com/miracle2k/python-glob2
    license: BSD-2-Clause
    license_file: LICENSE
    summary: Version of the glob module that supports recursion via **, and can capture
        patterns.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dfroger
