# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ipykernel-5.3.4-python_3.8-on-linux_64, last modified Fri Jul 31 14:41:26 2020
# ------------------------------------------------

package:
    name: ipykernel
    version: 5.3.4
source:
    sha256: 9b2652af1607986a1b231c62302d070bc0534f564c393a5d9d130db9abbbe89d
    url: https://pypi.io/packages/source/i/ipykernel/ipykernel-5.3.4.tar.gz
build:
    number: '0'
    script:
        - /tmp/build/80754af9/ipykernel_1596207638929/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
            setup.py bdist_wheel
        - cd dist
        - /tmp/build/80754af9/ipykernel_1596207638929/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
            -m pip install ipykernel-5.3.4-py3-none-any.whl --no-deps -vv
        - /tmp/build/80754af9/ipykernel_1596207638929/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
            -m ipykernel install --sys-prefix
    string: py38h5ca1d4c_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - backcall 0.2.0 py_0
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - decorator 4.4.2 py_0
        - ipython 7.16.1 py38h5ca1d4c_0
        - ipython_genutils 0.2.0 py38_0
        - jedi 0.17.1 py38_0
        - jupyter_client 6.1.6 py_0
        - jupyter_core 4.6.3 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libsodium 1.0.18 h7b6447c_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - parso 0.7.0 py_0
        - pexpect 4.8.0 py38_0
        - pickleshare 0.7.5 py38_1000
        - pip 20.1.1 py38_1
        - prompt-toolkit 3.0.5 py_0
        - ptyprocess 0.6.0 py38_0
        - pygments 2.6.1 py_0
        - python 3.8.3 hcff3b4d_2
        - python-dateutil 2.8.1 py_0
        - pyzmq 19.0.1 py38he6710b0_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.2.0 py38_0
        - six 1.15.0 py_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - tornado 6.0.4 py38h7b6447c_1
        - traitlets 4.3.3 py38_0
        - wcwidth 0.2.5 py_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zeromq 4.3.2 he6710b0_2
        - zlib 1.2.11 h7b6447c_3
    run:
        - ipython >=5.0
        - jupyter_client
        - python >=3.8,<3.9.0a0
        - tornado >=4.2
        - traitlets >=4.1
test:
    commands:
        - jupyter kernelspec list
    imports:
        - ipykernel
    requires:
        - curio
        - flaky
        - ipython
        - nose
        - numpy
        - pytest !=5.3.4
about:
    description: 'A powerful interactive Python shell and a Jupyter kernel to work
        with

        Python code in Jupyter notebooks and other interactive frontends.

        '
    dev_url: https://github.com/ipython/ipykernel
    doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
    doc_url: https://ipython.readthedocs.io
    home: https://ipython.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: IPython Kernel for Jupyter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - blink1073
        - bollwyvl
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
