# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Tue Oct 27 18:10:54 2020
# ------------------------------------------------

package:
    name: pyxdg
    version: '0.27'
source:
    fn: pyxdg-0.27.tar.gz
    sha256: 80bd93aae5ed82435f20462ea0208fb198d8eec262e831ee06ce9ddb6b91c5a5
    url: https://pypi.io/packages/source/p/pyxdg/pyxdg-0.27.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: pyhd3eb1b0_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py36hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - xdg
about:
    description: PyXDG is a python library to access freedesktop.org standards
    home: http://freedesktop.org/wiki/Software/pyxdg
    license: GNU Lesser General Public v2 (LGPLv2)
    license_family: LGPL
    license_file: COPYING
    summary: PyXDG contains implementations of freedesktop.org standards in python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - marcelotrevisani
