# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/matplotlib-base-3.3.2-python_3.8-on-linux_64, last modified Thu Oct 22 13:33:48 2020
# ------------------------------------------------

package:
    name: matplotlib-base
    version: 3.3.2
source:
    sha256: a17664009de73849906de076c1de60d2854d26325d012cdd0b5e75edb8bd8edb
    url: https://github.com/matplotlib/matplotlib/archive/v3.3.2.tar.gz
build:
    ignore_run_exports:
        - tk
    number: '0'
    string: py38h817c723_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - pkg-config 0.29.2 h1bed415_8
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py38_0
        - cycler 0.10.0 py38_0
        - freetype 2.10.4 h5ab3b9f_0
        - intel-openmp 2020.2 254
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libpng 1.6.37 hbc83047_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2020.2 256
        - mkl-service 2.3.0 py38he904b0f_0
        - mkl_fft 1.2.0 py38h23d657b_0
        - mkl_random 1.1.1 py38h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - nose 1.3.7 py38_2
        - numpy 1.16.6 py38hbc911f0_0
        - numpy-base 1.16.6 py38hde5b4d6_0
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py38_0
        - pyparsing 2.4.7 py_0
        - python 3.8.5 h7579374_1
        - python-dateutil 2.8.1 py_0
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - certifi >=2020.06.20
        - cycler >=0.10
        - freetype >=2.10.4,<3.0a0
        - kiwisolver >=1.0.1
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - numpy >=1.16.6,<2.0a0
        - pillow >=6.2.0
        - pyparsing >=2.0.3,!=2.0.4,!=2.1.2,!=2.1.6
        - python >=3.8,<3.9.0a0
        - python-dateutil >=2.1
        - setuptools
        - tk
        - tornado
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: LicenseRef-PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
