# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/ipython_genutils-feedstock/recipe, last modified Wed Oct 30 12:09:58 2019
# ------------------------------------------------

package:
    name: ipython_genutils
    version: 0.2.0
source:
    fn: ipython_genutils-0.2.0.tar.gz
    sha256: eb2e116e75ecef9d4d228fdc66af54269afa26ab4463042e33785b887c628ba8
    url: https://pypi.io/packages/source/i/ipython_genutils/ipython_genutils-0.2.0.tar.gz
build:
    number: '0'
    script: python setup.py install
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_0
        - readline 7.0 h7b6447c_5
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - ipython_genutils
        - ipython_genutils.testing
        - ipython_genutils.tests
about:
    description: 'General purpose utilities.

        '
    home: http://ipython.org
    license: BSD 3-Clause
    license_file: COPYING.md
    summary: vestigial utilities from IPython
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - minrk
        - msarahan
        - pelson
        - scopatz
        - takluyver
