# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Nov 11 17:56:41 2020
# ------------------------------------------------

package:
    name: numpydoc
    version: 1.1.0
source:
    fn: numpydoc-1.1.0.tar.gz
    sha256: c36fd6cb7ffdc9b4e165a43f67bf6271a7b024d0bb6b00ac468c9e2bfc76448e
    url: https://pypi.io/packages/source/n/numpydoc/numpydoc-1.1.0.tar.gz
build:
    noarch: python
    number: '1'
    script: /tmp/build/80754af9/numpydoc_1605117425582/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps -vv
    string: pyhd3eb1b0_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py39h06a4308_0
        - python 3.9.0 hcff3b4d_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.1 py39h06a4308_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - tzdata 2020d h14c3975_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
        - sphinx
test:
    imports:
        - numpydoc
about:
    home: https://github.com/numpy/numpydoc
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Numpy's Sphinx extensions
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jschueller
        - scopatz
