# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Thu Sep 24 14:49:21 2020
# ------------------------------------------------

package:
    name: cytoolz
    version: 0.11.0
source:
    sha256: c64f3590c3eb40e1548f0d3c6b2ccde70493d0b8dc6cc7f9f3fec0bb3dcd4222
    url: https://pypi.io/packages/source/c/cytoolz/cytoolz-0.11.0.tar.gz
build:
    number: '0'
    script: /tmp/build/80754af9/cytoolz_1600958986966/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv --global-option=--with-cython
    string: py38h7b6447c_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.21 py38he6710b0_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - python >=3.8,<3.9.0a0
        - toolz >=0.10.0
test:
    commands:
        - nosetests --with-doctest cytoolz
    imports:
        - cytoolz
        - cytoolz.curried
    requires:
        - nose
        - toolz 0.10.0.*
about:
    description: 'CyToolz is the Cython implementation of the toolz package, which
        provides

        high performance utility functions for iterables, functions, and

        dictionaries.

        '
    dev_url: https://github.com/pytoolz/cytoolz
    doc_source_url: https://github.com/pytoolz/cytoolz/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/cytoolz
    home: https://github.com/pytoolz/cytoolz
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Cython implementation of Toolz. High performance functional utilities
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - eriknw
        - jakirkham
        - jcrist
        - mrocklin
