# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pyodbc-4.0.30-python_3.8-on-linux_64, last modified Mon Feb 10 16:47:12 2020
# ------------------------------------------------

package:
    name: pyodbc
    version: 4.0.30
source:
    fn: pyodbc-4.0.30.tar.gz
    patches:
        - setup.patch
    sha256: 1be68880d64deffa6a57dca776be83d8367d81357642d24c8b2a3151921b7cd5
    url: https://github.com/mkleehammer/pyodbc/archive/4.0.30.tar.gz
build:
    number: '0'
    script: /tmp/build/80754af9/pyodbc_1581353498114/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps -vv
    string: py38he6710b0_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 20.0.2 py38_1
        - python 3.8.1 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 45.1.0 py38_0
        - sqlite 3.31.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - unixodbc 2.3.7 h14c3975_0
        - wheel 0.34.2 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - python >=3.8,<3.9.0a0
        - unixodbc >=2.3.7,<2.4.0a0
test:
    imports:
        - pyodbc
about:
    description: 'pyodbc is a Python DB API 2 module for ODBC. This project provides
        an

        up-to-date, convenient interface to ODBC using native data types like

        datetime and decimal.

        '
    dev_url: https://github.com/mkleehammer/pyodbc
    doc_source_url: https://github.com/mkleehammer/pyodbc/blob/master/docs/index.md
    doc_url: http://mkleehammer.github.io/pyodbc/
    home: https://github.com/mkleehammer/pyodbc
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: DB API Module for ODBC
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
