# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/mccabe-feedstock/recipe, last modified Mon Nov 11 16:11:30 2019
# ------------------------------------------------

package:
    name: mccabe
    version: 0.6.1
source:
    fn: mccabe-0.6.1.tar.gz
    sha256: dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f
    url: https://pypi.io/packages/source/m/mccabe/mccabe-0.6.1.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py38_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - atomicwrites 1.3.0 py_0
        - attrs 19.3.0 py_0
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - more-itertools 7.2.0 py38_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - packaging 19.2 py_0
        - pluggy 0.13.0 py38_0
        - py 1.8.0 py_0
        - pyparsing 2.4.2 py_0
        - pytest 5.2.1 py38_0
        - pytest-runner 5.1 py_0
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - six 1.12.0 py38_1000
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wcwidth 0.1.7 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - mccabe
about:
    dev_url: https://github.com/PyCQA/mccabe
    home: https://github.com/PyCQA/mccabe
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: McCabe complexity checker for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - jakirkham
        - ocefpaf
        - sigmavirus24
