# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/get_terminal_size-feedstock/recipe, last modified Sun Sep 17 15:35:06 2017
# ------------------------------------------------

package:
    name: get_terminal_size
    version: 1.0.0
build:
    string: haa9412d_0
requirements:
    build:
        - backports 1.0 py36hc49ede0_1
        - backports.shutil_get_terminal_size 1.0.0 py36heaf1f72_2
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libedit 3.1 heed3624_0
        - libffi 3.2.1 h4deb6c0_3
        - libgcc-ng 7.2.0 hcbc56d2_1
        - libstdcxx-ng 7.2.0 h24385c6_1
        - ncurses 6.0 h06874d7_1
        - openssl 1.0.2l hd940f6d_1
        - python 3.6.2 ha783207_11
        - readline 7.0 hac23ff0_3
        - sqlite 3.20.1 h6d8b0f3_1
        - tk 8.6.7 h5979e9b_1
        - xz 5.2.3 h2bcbf08_1
        - zlib 1.2.11 hfbfcf68_1
    run:
        - backports.shutil_get_terminal_size
test:
    imports:
        - backports
        - backports.shutil_get_terminal_size
about:
    description: 'backport of the get_terminal_size function from Python 3.3''s shutil.

        Unlike the original version it is written in pure Python rather than C,

        so it might be a tiny bit slower.

        '
    doc_source_url: https://github.com/chrippa/backports.shutil_get_terminal_size/blob/master/README.rst
    doc_url: https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size
    home: https://github.com/chrippa/backports.shutil_get_terminal_size
    license: MIT
    summary: Get the size of the terminal window.
extra:
    copy_test_source_files: true
    final: true
