# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: liblief
    version: 0.10.1
source:
    -   fn: lief-0.10.1.tar.gz
        patches:
            - 0001-python-Only-pass-NODEFAULTLIB-MSVCRT-when-not-BUILD_.patch
            - 0002-Fix-typo-BuildeVersion-BuildVersion-which-may-lead-t.patch
            - 0003-Export-BuildToolVersion.patch
            - 0004-Do-not-annotate-static-ELF-Parser-s-parse-function-a.patch
            - 0005-Update-LIEF_VERSION_PATCH-to-1-for-v0.10.1.patch
            - 0006-Call-the-C-DLL-libLIEF.dll-so-it-does-not-clash-with.patch
            - 0007-Add-LIEFOptions-for-BUILD_STATIC_LIBS-and-BUILD_SHAR.patch
            - 0008-Add-_DEBUG-when-CMAKE_BUILD_TYPE-matches-Debug.patch
            - 0009-Avoid-deprecated-get_config_var-SO-use-EXT_SUFFIX-lo.patch
        sha256: 6f30c98a559f137e08b25bcbb376c0259914b33c307b8b901e01ca952241d00a
        url: https://github.com/lief-project/LIEF/archive/0.10.1.tar.gz
build:
    number: 0
    run_exports:
        - liblief >=0.10.1,<0.11.0a0
    string: he6710b0_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2020.1.1 0
        - ccache 3.7.9 hfe4627d_0
        - cmake 3.14.0 h52cb24c_0
        - expat 2.2.6 he6710b0_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - krb5 1.17.1 h173b8e3_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libcurl 7.69.1 h20c2e04_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.9.0 h1ba5d50_1
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - ninja 1.9.0 py38hfd86e86_0
        - openssl 1.1.1g h7b6447c_0
        - pkg-config 0.29.2 h1bed415_8
        - python 3.8.2 hcf32534_0
        - readline 8.0 h7b6447c_0
        - rhash 1.3.8 h1ba5d50_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    files:
        - tests
    requires:
        - cmake
        - gcc_linux-64 7.3.0.*
        - gxx_linux-64 7.3.0.*
        - ninja
    script: run_test_liblief.sh
about:
    description: 'It turns out that many projects need to parse executable formats
        and they usually re-implement

        their own parser. Moreover these parsers are usually bound to one language.

        LIEF attempts to fill this void.

        '
    doc_source_url: https://github.com/lief-project/LIEF/tree/master/doc
    doc_url: https://lief.quarkslab.com/doc/stable/index.html
    home: https://lief.quarkslab.com/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: A cross platform library to parse, modify and abstract ELF, PE and MachO
        formats.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - mingwandroid
        - msarahan
