# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/scikit-learn-0.23.2-python_3.8-on-linux_64, last modified Tue Aug 25 17:32:06 2020
# ------------------------------------------------

package:
    name: scikit-learn
    version: 0.23.2
source:
    sha256: 26f56e0c5aac4811f5a90109c4eed0396ee196d8383608b9bf33129528e6fcfd
    url: https://github.com/scikit-learn/scikit-learn/archive/0.23.2.tar.gz
build:
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .  --verbose
    string: py38h0573a6f_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.21 py38he6710b0_0
        - intel-openmp 2020.1 217
        - joblib 0.16.0 py_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2020.1 217
        - mkl-service 2.3.0 py38he904b0f_0
        - mkl_fft 1.1.0 py38h23d657b_0
        - mkl_random 1.1.1 py38h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - numpy 1.14.6 py38h056ac22_4
        - numpy-base 1.14.6 py38hde5b4d6_4
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - scipy 1.5.2 py38h0b6359f_0
        - setuptools 49.6.0 py38_0
        - six 1.15.0 py_0
        - sqlite 3.33.0 h62c20be_0
        - threadpoolctl 2.1.0 pyh5ca1d4c_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - joblib >=0.11
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
        - scipy
        - threadpoolctl
test:
    commands:
        - export OPENBLAS_NUM_THREADS=1
        - export OMP_NUM_THREADS=1
        - pytest --timeout 300 -n 1 --verbose --pyargs sklearn -k "not (_not_a_real_test
            or test_sag_regressor_computed_correct or network or test_california_housing)"
    imports:
        - sklearn
    requires:
        - cython >=0.28.5
        - pytest >=3.3.0
        - pytest-timeout
        - pytest-xdist
about:
    home: http://scikit-learn.org/
    license: BSD-3-Clause
    license_file: COPYING
    summary: A set of python modules for machine learning and data mining
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - adrinjalali
        - amueller
        - astaric
        - jakirkham
        - jnothman
        - lesteve
        - msarahan
        - ocefpaf
        - ogrisel
        - rth
