# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pathtools-0.1.2-on-linux_64, last modified Tue Dec  3 22:45:41 2019
# ------------------------------------------------

package:
    name: pathtools
    version: 0.1.2
source:
    fn: pathtools-0.1.2.tar.gz
    sha256: 7c35c5421a39bb82e58018febd90e3b6e5db34c5443aaaf742b3f33d4655f1c0
    url: https://pypi.io/packages/source/p/pathtools/pathtools-0.1.2.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py27_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py27_0
        - python 2.7.17 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 42.0.2 py27_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - pathtools
about:
    description: 'Python API library for common path and pattern functionality.

        '
    doc_url: http://pythonhosted.org/pathtools
    home: https://github.com/gorakhargosh/pathtools
    license: MIT
    license_file: LICENSE
    summary: Path utilities for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
