# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/python-language-server-0.35.1-on-linux_64, last modified Fri Sep 18 18:40:33 2020
# ------------------------------------------------

package:
    name: python-language-server
    version: 0.35.1
source:
    sha256: 6e0c9a3b2ae98e0eb22e98ed6b3c4e190a6bf9e27af53efd2396da60cd92b221
    url: https://pypi.org/packages/source/p/python-language-server/python-language-server-0.35.1.tar.gz
build:
    entry_points:
        - pyls = pyls.__main__:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/python-language-server_1600454544709/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - autopep8
        - flake8 >=3.8.0
        - jedi >=0.17.0,<0.18.0a0
        - mccabe >=0.6.0,<0.7.0
        - pluggy
        - pycodestyle >=2.6.0,<2.7.0
        - pydocstyle >=2.0.0
        - pyflakes >=2.2.0,<2.3.0
        - pylint
        - python >=3.6
        - python-jsonrpc-server >=0.4.0
        - rope >=0.10.5
        - setuptools
        - ujson >=3.0
        - yapf
test:
    commands:
        - python -m pip check
        - pyls --help
    requires:
        - pip
about:
    description: 'A Python 2.7 and 3.4+ implementation of the Language Server Protocol

        making use of Jedi, pycodestyle, Pyflakes and YAPF.

        '
    dev_url: https://github.com/palantir/python-language-server
    home: https://github.com/palantir/python-language-server
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: An implementation of the Language Server Protocol for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - andfoy
        - ccordoba12
        - goanpeca
        - rlaverde
