# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Nov 11 19:08:10 2020
# ------------------------------------------------

package:
    name: pkginfo
    version: 1.6.1
source:
    fn: pkginfo-1.6.1.tar.gz
    sha256: a6a4ac943b496745cec21f14f021bbd869d5e9b4f6ec06918cffea5a2f4b9193
    url: https://pypi.io/packages/source/p/pkginfo/pkginfo-1.6.1.tar.gz
build:
    entry_points:
        - pkginfo = pkginfo.commandline:main
    number: '0'
    script: python setup.py install  --single-version-externally-managed --record=record.txt
    string: py38h06a4308_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.1 py38h06a4308_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    commands:
        - pkginfo --help
    imports:
        - pkginfo
        - pkginfo.tests
about:
    description: 'This package provides an API for querying the distutils metadata
        written in

        the ``PKG-INFO`` file inside a source distriubtion (an ``sdist``) or

        a binary distribution (e.g., created by running ``bdist_egg``)

        '
    dev_url: https://code.launchpad.net/~tseaver/pkginfo/trunk
    doc_url: http://pythonhosted.org/pkginfo/
    home: https://code.launchpad.net/~tseaver/pkginfo/trunk
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: Query metadatdata from sdists / bdists / installed packages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jankatins
        - mingwandroid
