# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zstd-1.4.5-on-linux_canary, last modified Tue Jul 28 19:22:16 2020
# ------------------------------------------------

package:
    name: zstd
    version: 1.4.5
source:
    fn: zstd-1.4.5.tar.gz
    sha256: 98e91c7c6bf162bf90e4e70fdbc41a8188b9fa8de5ad840c401198014406ce9e
    url: https://github.com/facebook/zstd/releases/download/v1.4.5/zstd-1.4.5.tar.gz
build:
    number: '0'
    run_exports:
        - zstd >=1.4.5,<1.4.6.0a0
    string: h9ceee32_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2020.6.24 0
        - cmake 3.14.0 h52cb24c_0
        - expat 2.2.9 he6710b0_2
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - krb5 1.18.2 h173b8e3_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libcurl 7.71.1 h20c2e04_1
        - libedit 3.1.20191231 h14c3975_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.9.0 h1ba5d50_1
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - rhash 1.3.8 h1ba5d50_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - lz4-c 1.9.2 he6710b0_1
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - lz4-c >=1.9.2,<1.10.0a0
        - xz >=5.2.5,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
about:
    description: 'Zstandard is a real-time compression algorithm, providing high compression

        ratios. It offers a very wide range of compression / speed trade-off, while

        being backed by a very fast decoder. It also offers a special mode for

        small data, called dictionary compression, and can create dictionaries from

        any sample set. Zstandard library is provided as open source software using

        a BSD license.

        '
    dev_url: https://github.com/facebook/zstd
    doc_url: https://facebook.github.io/zstd/zstd_manual.html
    home: http://www.zstd.net
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Zstandard - Fast real-time compression algorithm
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - rmax
        - xhochy
