# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pango-1.45.3-on-linux_64, last modified Sat Jun 27 20:56:05 2020
# ------------------------------------------------

package:
    name: pango
    version: 1.45.3
source:
    sha256: 1f75c1ebab3d298bb0c18f420440b507a95ce4b98905274f4af80831ff7ee67d
    url: http://ftp.gnome.org/pub/GNOME/sources/pango/1.45/pango-1.45.3.tar.xz
build:
    detect_binary_files_with_prefix: true
    ignore_run_exports:
        - libgcc-ng
        - libstdcxx-ng
    number: '0'
    run_exports:
        - pango >=1.45.3,<2.0a0
    string: hd140c19_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - ca-certificates 2020.6.24 0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxcb-cos6-x86_64 1.12 h6fd0490_0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
        - make 4.2.1 h1bed415_1
        - meson 0.52.0 py_0
        - ncurses 6.2 he6710b0_1
        - ninja 1.9.0 py38hfd86e86_0
        - openssl 1.1.1g h7b6447c_0
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - cairo 1.14.12 h8948797_3
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_1
        - fribidi 1.0.9 h7b6447c_0
        - glib 2.65.0 h3eb4bd4_0
        - gobject-introspection 1.56.1 py38h56ee657_3
        - graphite2 1.3.14 h23475e2_0
        - harfbuzz 2.4.0 hca77d97_1
        - icu 58.2 he6710b0_3
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libpng 1.6.37 hbc83047_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuuid 1.0.3 h1bed415_2
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.10 he19cac6_1
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pcre 8.44 he6710b0_0
        - pixman 0.40.0 h7b6447c_0
        - pkg-config 0.29.2 h1bed415_8
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - cairo >=1.14.12,<2.0a0
        - fontconfig >=2.13.0,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - fribidi >=1.0.9,<2.0a0
        - glib >=2.65.0,<3.0a0
        - harfbuzz >=2.4.0,<3.0a0
        - libgcc-ng >=7.3.0
test:
    commands:
        - pango-list --help
        - pango-view --help
        - test -f $PREFIX/share/gir-1.0/Pango-1.0.gir
about:
    description: 'Pango is a library for laying out and rendering of text, with an
        emphasis

        on internationalization. Pango can be used anywhere that text layout is

        needed, though most of the work on Pango so far has been done in the

        context of the GTK+ widget toolkit. Pango forms the core of text and font

        handling for GTK+-2.x.

        '
    dev_url: https://github.com/phuang/pango
    doc_url: http://www.pango.org/
    home: http://www.pango.org/
    license: LGPL-2.1
    license_file: COPYING
    summary: Text layout and rendering engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - chenghlee
        - jakirkham
        - ocefpaf
        - pkgw
