# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri Sep 18 20:22:09 2020
# ------------------------------------------------

package:
    name: pyzmq
    version: 19.0.2
source:
    sha256: 296540a065c8c21b26d63e3cea2d1d57902373b16e4256afe46422691903a438
    url: https://pypi.io/packages/source/p/pyzmq/pyzmq-19.0.2.tar.gz
build:
    ignore_run_exports:
        - libgcc-ng
        - libsodium
        - libstdcxx-ng
    number: '1'
    string: py38he6710b0_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - pkg-config 0.29.2 h1bed415_8
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libsodium 1.0.18 h7b6447c_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zeromq 4.3.2 he6710b0_3
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - python >=3.8,<3.9.0a0
        - zeromq >=4.3.2,<4.4.0a0
        - zeromq >=4.3.2,<4.4.0a0
test:
    commands:
        - py.test --pyargs zmq.tests.test_socket
    imports:
        - zmq
        - zmq.backend.cython.socket
        - zmq.backend.cython.utils
        - zmq.devices.monitoredqueue
    requires:
        - pytest
about:
    description: 'PyZMQ contains Python bindings for 0MQ. 0MQ is a lightweight and
        fast

        messaging implementation.

        '
    dev_url: https://github.com/zeromq/pyzmq
    doc_source_url: https://github.com/zeromq/pyzmq/blob/master/docs/source/index.rst
    doc_url: https://pyzmq.readthedocs.org/
    home: https://github.com/zeromq/pyzmq
    license: BSD 3-clause
    license_family: BSD
    license_file: COPYING.BSD
    summary: Python bindings for zeromq
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - JohanMabille
        - SylvainCorlay
        - chenghlee
        - jakirkham
        - mingwandroid
        - minrk
        - msarahan
        - ocefpaf
        - pelson
