# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/argh-0.26.2-python_3.8-on-linux_64, last modified Tue Dec  3 23:15:12 2019
# ------------------------------------------------

package:
    name: argh
    version: 0.26.2
source:
    fn: argh-0.26.2.tar.gz
    sha256: e9535b8c84dc9571a48999094fda7f33e63c3f1b74f3e5f3ac0105a58405bb65
    url: https://pypi.io/packages/source/a/argh/argh-0.26.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 42.0.2 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - argh
about:
    description: 'An argparse wrapper that doesn''t make you say "argh" each time
        you deal with it.

        '
    doc_url: http://argh.readthedocs.io/en/latest/
    home: https://github.com/neithere/argh
    license: LGPL 3
    summary: The Natural CLI.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - daler
        - goanpeca
