# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pytables-3.6.1-python_3.8-on-linux_64, last modified Tue Jan 28 22:34:11 2020
# ------------------------------------------------

package:
    name: pytables
    version: 3.6.1
source:
    sha256: 49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49
    url: https://pypi.io/packages/source/t/tables/tables-3.6.1.tar.gz
build:
    entry_points:
        - pt2to3 = tables.scripts.pt2to3:main
        - ptdump = tables.scripts.ptdump:main
        - ptrepack = tables.scripts.ptrepack:main
        - pttree = tables.scripts.pttree:main
    number: '0'
    string: py38h9fd0a39_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - blosc 1.16.3 hd408876_0
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - cython 0.29.14 py38he6710b0_0
        - hdf5 1.10.4 hb1b8bf9_0
        - intel-openmp 2019.4 243
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - lz4-c 1.8.1.2 h14c3975_0
        - lzo 2.10 h49e0be7_2
        - mkl 2019.4 243
        - mkl-service 2.3.0 py38he904b0f_0
        - mkl_fft 1.0.15 py38ha843d7b_0
        - mkl_random 1.1.0 py38h962f231_0
        - ncurses 6.1 he6710b0_1
        - numexpr 2.7.0 py38hd81dba3_0
        - numpy 1.14.6 py38h056ac22_4
        - numpy-base 1.14.6 py38hde5b4d6_4
        - openssl 1.1.1d h7b6447c_3
        - pip 20.0.2 py38_0
        - python 3.8.1 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 45.1.0 py38_0
        - six 1.14.0 py38_0
        - snappy 1.1.7 hbae5bb6_3
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.3.7 h0b5b093_0
    run:
        - blosc >=1.16.3,<2.0a0
        - bzip2 >=1.0.8,<2.0a0
        - hdf5 >=1.10.4,<1.10.5.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - lzo >=2.10,<3.0a0
        - mock
        - numexpr
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
        - six
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - pt2to3 -h
        - ptdump -h
        - ptrepack -h
        - pttree -h
    requires:
        - mock
        - setuptools
about:
    description: 'PyTables is a package for managing hierarchical datasets and designed
        to

        efficiently and easily cope with extremely large amounts of data. PyTables

        is built on top of the HDF5 library, using the Python language and the

        NumPy package.

        '
    dev_url: https://github.com/PyTables
    doc_url: http://www.pytables.org/
    home: http://www.pytables.org
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Brings together Python, HDF5 and NumPy to easily handle large amounts
        of data.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - scopatz
        - tomkooij
