# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/bkcharts-0.2-python_3.8-on-linux_64, last modified Wed Aug  7 19:26:18 2019
# ------------------------------------------------

package:
    name: bkcharts
    version: '0.2'
source:
    fn: bkcharts-0.2.tar.gz
    sha256: a5eaa8e78853dcecaa46345812e4fabe9cd3b96330ebf0809f640a4a0556d72e
    url: https://pypi.io/packages/source/b/bkcharts/bkcharts-0.2.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.1 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 45.1.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - numpy >=1.7.1
        - pandas
        - python >=3.8,<3.9.0a0
        - six >=1.5.2
about:
    dev_url: http://github.com/bokeh/bkcharts
    home: http://github.com/bokeh/bkcharts
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: High level chart types built on top of Bokeh
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
