# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/pickleshare-feedstock/recipe, last modified Mon Nov 11 16:22:21 2019
# ------------------------------------------------

package:
    name: pickleshare
    version: 0.7.5
source:
    sha256: 87683d47965c1da65cdacaf31c8441d12b8044cdec9aca500cd78fc2c683afca
    url: https://pypi.io/packages/source/p/pickleshare/pickleshare-0.7.5.tar.gz
build:
    number: '1000'
    script: /tmp/build/80754af9/pickleshare_1573489523607/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py38_1000
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - pickleshare
about:
    description: 'PickleShare is a small "shelve" like datastore with concurrency
        support.

        Like shelve, a PickleShareDB object acts like a normal dictionary. Unlike

        shelve, many processes can access the database simultaneously. Changing a

        value in database is immediately visible to other processes accessing the

        same database.

        '
    dev_url: https://github.com/pickleshare/pickleshare
    doc_source_url: https://github.com/pickleshare/pickleshare/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/pickleshare
    home: https://github.com/pickleshare/pickleshare/
    license: MIT
    license_file: LICENSE
    summary: Tiny 'shelve'-like database with concurrency support
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pelson
        - takluyver
