# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/h5py-2.10.0-python_3.8-on-linux_64, last modified Wed Jan 29 00:59:33 2020
# ------------------------------------------------

package:
    name: h5py
    version: 2.10.0
source:
    sha256: 2a8369f74d079dbfe35aebbf56b565a5d2e7bea6d3cdba682b4d456128a23b5e
    url: https://github.com/h5py/h5py/archive/2.10.0.tar.gz
build:
    number: '0'
    string: py38h7918eee_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - cython 0.29.14 py38he6710b0_0
        - hdf5 1.10.4 hb1b8bf9_0
        - intel-openmp 2019.4 243
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2019.4 243
        - mkl-service 2.3.0 py38he904b0f_0
        - ncurses 6.1 he6710b0_1
        - numpy-base 1.11.3 py38hde5b4d6_12
        - numpy-devel 1.11.3 py38h4ba5984_12
        - openssl 1.1.1d h7b6447c_3
        - pip 20.0.2 py38_0
        - pkg-config 0.29.2 h1bed415_8
        - pkgconfig 1.4.0 py38_0
        - python 3.8.1 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 45.1.0 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - hdf5 >=1.10.4,<1.10.5.0a0
        - libgcc-ng >=7.3.0
        - numpy >=1.11.3,<2.0a0
        - python >=3.8,<3.9.0a0
        - six
test:
    imports:
        - h5py
    requires:
        - pytest
about:
    description: 'H5py uses straightforward NumPy and Python metaphors, like dictionary
        and

        NumPy array syntax.

        '
    dev_url: https://github.com/h5py/h5py
    doc_url: http://docs.h5py.org
    home: http://www.h5py.org/
    license: BSD-3-Clause
    license_file: licenses/license.txt
    summary: Read and write HDF5 files from Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - pitrou
        - tacaswell
