# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Sat Oct 31 00:11:12 2020
# ------------------------------------------------

package:
    name: pygments
    version: 2.7.2
source:
    sha256: 381985fcc551eb9d37c52088a32914e00517e57f4a21609f48141ba08e193fa0
    url: https://pypi.io/packages/source/P/Pygments/Pygments-2.7.2.tar.gz
build:
    entry_points:
        - pygmentize = pygments.cmdline:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/pygments_1604103097372/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps -vv
    string: pyhd3eb1b0_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.5
        - setuptools
test:
    commands:
        - pip check
        - pygmentize -h
    imports:
        - pygments
        - pygments.filters
        - pygments.formatters
        - pygments.lexers
        - pygments.plugin
        - pygments.styles
    requires:
        - pip
about:
    home: http://pygments.org/
    license: BSD-2-clause
    license_file: LICENSE
    summary: Pygments is a generic syntax highlighter suitable for use in code hosting,
        forums, wikis or other applications that need to prettify source code.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - ocefpaf
        - pelson
        - scopatz
