# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/cycler-feedstock/recipe, last modified Thu Nov 14 14:22:35 2019
# ------------------------------------------------

package:
    name: cycler
    version: 0.10.0
source:
    fn: cycler-v0.10.0.tar.gz
    sha256: b6d217635e03024196225367b1a438996dbbf0271bec488f00584f0e7dc15cfa
    url: https://github.com/matplotlib/cycler/archive/v0.10.0.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - six 1.13.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
        - six
test:
    imports:
        - cycler
about:
    description: 'Cycler is a package used to create composable style cycles.

        '
    dev_url: https://github.com/matplotlib/cycler
    doc_source_url: https://github.com/matplotlib/cycler/blob/master/doc/source/index.rst
    doc_url: http://matplotlib.org/cycler/
    home: http://matplotlib.org/cycler
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Composable style cycles.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - janschulz
        - ocefpaf
        - pelson
        - tacaswell
