# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/dbus-1.13.18-on-linux_64, last modified Wed Oct 14 18:42:19 2020
# ------------------------------------------------

package:
    name: dbus
    version: 1.13.18
source:
    patches:
        - patches/0001-Add-var-lib-dbus-machine-id-as-a-fallback.patch
        - patches/0002-Make-it-possible-to-read-files-on-proc-which-reports.patch
        - patches/0003-Use-proc-sys-kernel-random-boot_id-as-last-resort-fa.patch
        - patches/0004-disable-fd-limit-tests-not-supported-in-docker.patch
    sha256: 8078f5c25e34ab907ce06905d969dc8ef0ccbec367e1e1707c7ecf8460f4254e
    url: http://dbus.freedesktop.org/releases/dbus/dbus-1.13.18.tar.xz
build:
    ignore_run_exports:
        - glib
        - libgcc-ng
    number: '0'
    run_exports:
        - dbus >=1.13.18,<2.0a0
    string: hb2f20db_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
        - pkg-config 0.29.2 h1bed415_8
    host:
        - _libgcc_mutex 0.1 main
        - expat 2.2.10 he6710b0_2
        - glib 2.65.0 h3eb4bd4_0
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - pcre 8.44 he6710b0_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - expat >=2.2.10,<3.0a0
        - glib
        - libgcc-ng >=7.3.0
test:
    commands:
        - dbus-daemon --version
        - dbus-uuidgen
about:
    description: 'D-Bus is a message bus system, a simple way for applications

        to talk to one another. In addition to interprocess communication, D-Bus helps

        coordinate process lifecycle; it makes it simple and reliable to code a "single

        instance" application or daemon, and to launch applications and daemons on

        demand when their services are needed.

        '
    dev_url: git://anongit.freedesktop.org/dbus/dbus
    doc_source_url: https://cgit.freedesktop.org/dbus/dbus/tree/doc
    doc_url: https://www.freedesktop.org/wiki/IntroductionToDBus/
    home: http://www.freedesktop.org/wiki/Software/dbus/
    license: GPL2
    license_file: COPYING
    summary: Simple message bus system for applications to talk to one another
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - nehaljwani
        - ocefpaf
