# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Nov 11 15:25:46 2020
# ------------------------------------------------

package:
    name: babel
    version: 2.8.1
source:
    fn: Babel-2.8.1.tar.gz
    sha256: 820c195271534e8a86f564ba9ef2c207f356cfeb7e94d2bdc6b57897c4233837
    url: https://pypi.io/packages/source/B/Babel/Babel-2.8.1.tar.gz
build:
    entry_points:
        - pybabel = babel.messages.frontend:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/babel_1605108370292/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps -vv
    string: pyhd3eb1b0_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py36h06a4308_0
        - python 3.6.12 hcff3b4d_2
        - pytz 2020.1 py_0
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.1 py36h06a4308_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
        - pytz
test:
    commands:
        - pybabel --help
    imports:
        - babel
        - babel.localtime
        - babel.messages
about:
    description: 'Babel is an integrated collection of utilities that assist in

        internationalizing and localizing Python applications, with an emphasis

        on web-base applications.

        '
    dev_url: https://github.com/python-babel/babel
    doc_source_url: https://github.com/python-babel/babel/blob/master/docs/index.rst
    doc_url: http://babel.pocoo.org/en/latest/#user-documentation
    home: http://babel.pocoo.org/
    license: BSD 3-clause
    license_file: LICENSE
    summary: Utilities to internationalize and localize Python applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - frol
        - nehaljwani
