# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/backports-1.0-on-linux_canary, last modified Tue Jun 11 14:34:54 2019
# ------------------------------------------------

package:
    name: backports
    version: '1.0'
build:
    noarch: python
    number: '2'
    string: py_2
requirements:
    host:
        - ca-certificates 2019.5.15 0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1c h7b6447c_1
        - python 2.7.16 h9bab390_0
        - readline 7.0 h7b6447c_5
        - sqlite 3.28.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    imports:
        - backports
about:
    description: 'Namespace for backported Python features.

        '
    doc_source_url: https://bitbucket.org/brandon/backports/src/931d2c348a93313413e444c0724db7ac5030a496/setup.py?at=default&fileviewer=file-view-default
    doc_url: https://pypi.python.org/pypi/backports/
    home: https://bitbucket.org/brandon/backports
    license: BSD
extra:
    copy_test_source_files: true
    final: true
