# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/clyent-feedstock/recipe, last modified Mon Nov 18 17:17:41 2019
# ------------------------------------------------

package:
    name: clyent
    version: 1.2.2
source:
    fn: clyent-1.2.2.tar.gz
    sha256: a4c33bd70fd3c53f133eb301db7b83acb7cbe6d1e405158b8f5582aa888d3aa3
    url: https://github.com/Anaconda-Platform/clyent/archive/1.2.2.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py38_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
        - setuptools
test:
    imports:
        - clyent
about:
    description: 'Clyent is a python command line utility library for binstar,

        binstar-build, and chalmers.

        '
    dev_url: hhttps://github.com/Anaconda-Platform/clyent
    doc_source_url: https://github.com/Anaconda-Platform/clyent/blob/master/README.md
    doc_url: https://pypi.python.org/pypi/clyent
    home: https://github.com/Anaconda-Platform/clyent
    license: BSD 3-Clause
    summary: Command line client library for windows and posix
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
        - nehaljwani
