# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/backports.tempfile-1.0-on-linux_canary, last modified Tue Jun 11 14:36:10 2019
# ------------------------------------------------

package:
    name: backports.tempfile
    version: '1.0'
source:
    fn: backports.tempfile-1.0.tar.gz
    sha256: 1c648c452e8770d759bdc5a5e2431209be70d25484e1be24876cf2168722c762
    url: https://pypi.io/packages/source/b/backports.tempfile/backports.tempfile-1.0.tar.gz
build:
    noarch: python
    number: '1'
    script: /tmp/build/80754af9/backports.tempfile_1560268174108/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - backports 1.0 py_2
        - backports.weakref 1.0.post1 py27_0
        - ca-certificates 2019.5.15 0
        - certifi 2019.3.9 py27_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1c h7b6447c_1
        - pip 19.1.1 py27_0
        - python 2.7.16 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.0.1 py27_0
        - setuptools_scm 3.3.3 py_0
        - sqlite 3.28.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.4 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - backports
        - backports.weakref
        - python
test:
    imports:
        - backports.tempfile
about:
    description: "This package provides backports of new features in Python\u2019\
        s tempfile module under the backports namespace.\n"
    home: https://github.com/pjdelport/backports.tempfile
    license: PSF 2
    license_file: LICENSE
    summary: Backports of new features in Python's tempfile module
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mvdbeek
