# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/krb5-1.18.2-on-linux_64, last modified Mon Jun 29 13:11:55 2020
# ------------------------------------------------

package:
    name: krb5
    version: 1.18.2
source:
    sha256: 3a92fb44d06a60a79c71a031a528246bf4cf3badad150a2b91dfa7c4702c6c19
    url: https://github.com/krb5/krb5/archive/krb5-1.18.2-final.tar.gz
build:
    ignore_run_exports:
        - libgcc-ng
        - libstdcxx-ng
        - tk
    number: '0'
    run_exports:
        - krb5 >=1.18.2,<1.19.0a0
    string: h173b8e3_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526hebd4dad_5
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - bison 3.4 he6710b0_1
        - ca-certificates 2020.1.1 0
        - flex 2.6.4 ha10e3a4_1
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - perl 5.26.2 h14c3975_0
        - pkg-config 0.29.2 h1bed415_8
        - python 3.7.7 hcff3b4d_5
        - readline 8.0 h7b6447c_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - libedit 3.1.20191231 h7b6447c_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - tk 8.6.10 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libedit >=3.1.20191231,<3.2.0a0
        - libedit >=3.1.20191231,<4.0a0
        - libgcc-ng >=7.3.0
        - openssl >=1.1.1g,<1.1.2a
test:
    commands:
        - conda inspect linkages -p $PREFIX krb5
    requires:
        - python 3.7.*
about:
    home: http://web.mit.edu/kerberos/
    license: MIT
    license_file: doc/notice.rst
    summary: A network authentication protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chenghlee
        - mariusvniekerk
        - mingwandroid
        - ocefpaf
        - pelson
