# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/bottleneck-1.3.2-python_3.8-on-linux_canary, last modified Wed Jun 10 09:01:46 2020
# ------------------------------------------------

package:
    name: bottleneck
    version: 1.3.2
source:
    sha256: 20179f0b66359792ea283b69aa16366419132f3b6cf3adadc0c48e2e8118e573
    url: https://pypi.io/packages/source/B/Bottleneck/Bottleneck-1.3.2.tar.gz
build:
    number: '1'
    script: /tmp/build/80754af9/bottleneck_1591779921617/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . -vv
    string: py38heb32a55_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - intel-openmp 2020.1 217
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2020.1 217
        - mkl-service 2.3.0 py38he904b0f_0
        - mkl_fft 1.0.15 py38ha843d7b_0
        - mkl_random 1.1.1 py38h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - numpy 1.14.6 py38h056ac22_4
        - numpy-base 1.14.6 py38hde5b4d6_4
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py38_3
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 47.1.1 py38_0
        - six 1.15.0 py_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py38_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - numpy >=1.14.6,<2.0a0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - python -c "import bottleneck; bottleneck.test()"
    imports:
        - bottleneck
        - bottleneck.move
        - bottleneck.nonreduce
        - bottleneck.nonreduce_axis
        - bottleneck.reduce
        - bottleneck.slow
        - bottleneck.tests
    requires:
        - pytest
about:
    description: 'Bottleneck is a collection of fast NumPy array functions written
        in

        Cython.

        '
    dev_url: https://github.com/pydata/bottleneck
    doc_url: https://bottleneck.readthedocs.io
    home: https://github.com/pydata/bottleneck
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Fast NumPy array functions written in Cython.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - qwhelan
        - wesm
