# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Oct 12 17:21:32 2020
# ------------------------------------------------

package:
    name: ujson
    version: 4.0.1
source:
    fn: ujson-4.0.1.tar.gz
    sha256: 26cf6241b36ff5ce4539ae687b6b02673109c5e3efc96148806a7873eaa229d3
    url: https://pypi.io/packages/source/u/ujson/ujson-4.0.1.tar.gz
build:
    number: '0'
    script: /tmp/build/80754af9/ujson_1602523317881/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . -vv
    string: py38he6710b0_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - python >=3.8,<3.9.0a0
test:
    imports:
        - ujson
about:
    dev_url: https://github.com/ultrajson/ultrajson
    home: https://github.com/ultrajson/ultrajson
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Ultra fast JSON decoder and encoder written in C with Python bindings
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kszucs
        - synapticarbors
