# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/aggregate/mistune-feedstock/recipe, last modified Mon Nov 11 16:11:30 2019
# ------------------------------------------------

package:
    name: mistune
    version: 0.8.4
source:
    sha256: 59a3429db53c50b5c6bcc8a07f8848cb00d7dc8bdb431a4ab41920d201d4756e
    url: https://pypi.io/packages/source/m/mistune/mistune-0.8.4.tar.gz
build:
    number: '1000'
    script: python -m pip install --no-deps --ignore-installed .
    string: py38h7b6447c_1000
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - cython 0.29.13 py38he6710b0_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h0371630_2
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - python >=3.8,<3.9.0a0
test:
    commands:
        - nosetests
    imports:
        - mistune
    requires:
        - nose
        - python >=3.8,<3.9.0a0
    source_files:
        - tests
about:
    description: 'Inspired by https://github.com/chjj/marked, Mistune is the fastest
        markdown

        parser in pure Python with renderer features. More features include table,

        footnotes, autolink, fenced code etc.

        '
    dev_url: https://github.com/lepture/mistune
    doc_source_url: https://github.com/lepture/mistune/blob/master/README.rst
    doc_url: https://mistune.readthedocs.io/
    home: https://github.com/lepture/mistune
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: The fastest markdown parser in pure Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - ocefpaf
        - pelson
