# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Sep 30 18:33:32 2020
# ------------------------------------------------

package:
    name: keyring
    version: 21.4.0
source:
    sha256: 9aeadd006a852b78f4b4ef7c7556c2774d2432bbef8ee538a3e9089ac8b11466
    url: https://pypi.io/packages/source/k/keyring/keyring-21.4.0.tar.gz
build:
    entry_points:
        - keyring = keyring.cli:main
    number: '1'
    script: /tmp/build/80754af9/keyring_1601490835422/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps -vv
    string: py38_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.2 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py38_1
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - toml 0.10.1 py_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.8,<3.9.0a0
        - secretstorage
test:
    commands:
        - pip check
        - py.test -v tests
        - keyring --help
    imports:
        - keyring
        - keyring.backends
        - keyring.util
    requires:
        - pip
        - pytest >=2.8
        - pytest-runner
        - setuptools_scm >=1.15.0
    source_files:
        - tests/*
about:
    description: 'the python keyring lib provides a easy way to access the system
        keyring

        service from python.  it can be used in any application that needs safe

        password storage.

        '
    doc_source_url: https://github.com/jaraco/keyring/blob/master/readme.rst
    doc_url: https://pypi.org/project/keyring/
    home: https://github.com/jaraco/keyring
    license: Python Software Foundation or MIT
    license_family: MIT
    license_file: LICENSE
    summary: Store and access your passwords safely
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - ericdill
        - licode
        - tacaswell
