# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Thu Oct  8 19:12:50 2020
# ------------------------------------------------

package:
    name: pytest
    version: 6.1.1
source:
    sha256: 8f593023c1a0f916110285b6efd7f99db07d59546e3d8c36fc60e2ab05d3be92
    url: https://pypi.io/packages/source/p/pytest/pytest-6.1.1.tar.gz
build:
    entry_points:
        - py.test = py.test:main
        - pytest = py.test:main
    number: '0'
    script: /tmp/build/80754af9/pytest_1602184395338/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        setup.py install --single-version-externally-managed --record record.txt
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - attrs >=17.4.0
        - iniconfig
        - more-itertools >=4.0.0
        - packaging
        - pluggy >=0.12,<1.0
        - py >=1.8.2
        - python >=3.8,<3.9.0a0
        - toml
    run_constrained:
        - pytest-faulthandler >=2
test:
    commands:
        - pytest -h
    imports:
        - pytest
about:
    description: 'The pytest framework makes it easy to write small tests, yet scales
        to

        support complex functional testing for applications and libraries.

        '
    dev_url: https://github.com/pytest-dev/pytest/
    doc_url: https://docs.pytest.org/en/latest/
    home: https://docs.pytest.org/en/latest/
    license: MIT
    license_file: LICENSE
    summary: Simple and powerful testing with Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - flub
        - goanpeca
        - mingwandroid
        - nicoddemus
        - ocefpaf
