# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/astropy-4.0.2-python_3.8-on-linux_64, last modified Tue Oct 13 15:09:10 2020
# ------------------------------------------------

package:
    name: astropy
    version: 4.0.2
source:
    sha256: 4014e472cc7d3ca225524bf56bf4087042cc564849cfc528c435414c2f2f4b7e
    url: https://pypi.io/packages/source/a/astropy/astropy-4.0.2.tar.gz
build:
    detect_binary_files_with_prefix: false
    entry_points:
        - fits2bitmap = astropy.visualization.scripts.fits2bitmap:main
        - fitscheck = astropy.io.fits.scripts.fitscheck:main
        - fitsdiff = astropy.io.fits.scripts.fitsdiff:main
        - fitsheader = astropy.io.fits.scripts.fitsheader:main
        - fitsinfo = astropy.io.fits.scripts.fitsinfo:main
        - samp_hub = astropy.samp.hub_script:hub_script
        - volint = astropy.io.votable.volint:main
        - wcslint = astropy.wcs.wcslint:main
    number: '0'
    string: py38h7b6447c_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.14 py38he6710b0_0
        - intel-openmp 2020.2 254
        - jinja2 2.10.3 py_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - markupsafe 1.1.1 py38h7b6447c_0
        - mkl 2020.2 256
        - mkl-service 2.3.0 py38he904b0f_0
        - mkl_fft 1.2.0 py38h23d657b_0
        - mkl_random 1.1.1 py38h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - numpy 1.16.6 py38hbc911f0_0
        - numpy-base 1.16.6 py38hde5b4d6_0
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - numpy >=1.16.6,<2.0a0
        - python >=3.8,<3.9.0a0
        - setuptools
test:
    commands:
        - fits2bitmap --help
        - fitscheck --help
        - fitsdiff --help
        - fitsheader --help
        - fitsinfo --help
        - samp_hub --help
        - volint --help
        - wcslint --help
    imports:
        - astropy
    requires:
        - pytest-astropy
about:
    description: 'The Astropy Project is a community effort to develop a single package
        for

        Astronomy in Python. It contains core functionality and common tools

        needed for performing astronomy and astrophysics research with Python.

        '
    dev_url: https://github.com/astropy/astropy
    doc_url: http://docs.astropy.org/en/stable/
    home: http://www.astropy.org/
    license: BSD-3-Clause
    license_file: LICENSE.rst
    summary: Community-developed Python Library for Astronomy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - astrofrog-conda-forge
        - bsipocz
        - mwcraig
