# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/navigator-updater-0.2.1-python_3.8-on-linux_64, last modified Tue Jun 30 22:25:00 2020
# ------------------------------------------------

package:
    name: navigator-updater
    version: 0.2.1
source:
    git_rev: v0.2.1
    git_url: https://github.com/ContinuumIO/navigator-updater.git
build:
    entry_points:
        - navigator-updater = navigator_updater.app.main:main
    osx_is_app: true
    string: py38_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.6.24 0
        - certifi 2020.6.20 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h7b6447c_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - python 3.8.3 hcff3b4d_0
        - readline 8.0 h7b6447c_0
        - setuptools 47.3.1 py38_0
        - sqlite 3.32.3 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - pyqt >=5.6
        - python >=3.8,<3.9.0a0
        - qtpy >=1.2
test:
    commands:
        - navigator-updater --help
    imports:
        - navigator_updater
about:
    home: https://github.com/ContinuumIO/navigator-updater
    license: proprietary - Continuum Analytics, Inc.
    license_family: Proprietary
    summary: Anaconda Navigator Updater
extra:
    copy_test_source_files: true
    final: true
