# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/glib-2.66.1-python_3.6-on-linux_64, last modified Wed Oct 14 20:57:34 2020
# ------------------------------------------------

package:
    name: glib
    version: 2.66.1
source:
    patches:
        - patches/0001-replace-hardcoded-paths.patch
        - patches/0002-skip-some-tests.patch
        - patches/0003-add-install_rpath-to-meson-build-files.patch
    sha256: a269ffe69fbcc3a21ff1acb1b6146b2a5723499d6e2de33ae16ccb6d2438ef60
    url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.66/glib-2.66.1.tar.xz
build:
    number: '0'
    run_exports:
        - glib >=2.66.1,<3.0a0
    string: h92f7085_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 py38_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - meson 0.55.3 py_0
        - ncurses 6.2 he6710b0_1
        - ninja 1.10.1 py38hfd86e86_0
        - openssl 1.1.1h h7b6447c_0
        - pkg-config 0.29.2 h1bed415_8
        - python 3.8.5 h7579374_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pcre 8.44 he6710b0_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libffi >=3.3,<3.4.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - pcre >=8.44,<9.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libglib-2.0.so
        - test ! -f ${PREFIX}/lib/libgobject-2.0.la
        - gapplication help
        - gdbus help
        - gio version
        - gio-querymodules .
        - glib-compile-resources --help
        - glib-compile-schemas --help
        - gobject-query --help
        - gresource help
        - gtester --help
about:
    description: 'GLib provides the core application building blocks for libraries
        and

        applications written in C. It provides the core object system used in

        GNOME, the main loop implementation, and a large set of utility functions

        functions for strings and common data structures.

        '
    dev_url: https://git.gnome.org/browse/glib/
    doc_source_url: https://git.gnome.org/browse/glib/tree/docs
    doc_url: https://developer.gnome.org/glib/unstable/
    home: https://developer.gnome.org/glib/
    license: LGPL-2.1
    license_file: COPYING
    summary: Provides core application building blocks for libraries and applications
        written in C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - chenghlee
        - isuruf
        - jakirkham
        - ocefpaf
        - pkgw
        - scopatz
