# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri Oct  9 21:49:34 2020
# ------------------------------------------------

package:
    name: statsmodels
    version: 0.12.0
source:
    sha256: 5c7d6707ad3112b67f564abaf1845d3c02ecc7174c2d990d539f45c37e98ad35
    url: https://pypi.io/packages/source/s/statsmodels/statsmodels-0.12.0.tar.gz
build:
    number: '0'
    script:
        - /tmp/build/80754af9/statsmodels_1602280205159/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
            -m pip install . --no-deps --ignore-installed -vvv
        - rm -f ${PREFIX}/LICENSE.txt
        - rm -f ${PREFIX}/setup.cfg
    string: py38h7b6447c_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py38_0
        - cython 0.29.21 py38he6710b0_0
        - intel-openmp 2020.2 254
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2020.2 256
        - mkl-service 2.3.0 py38he904b0f_0
        - mkl_fft 1.2.0 py38h23d657b_0
        - mkl_random 1.1.1 py38h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - numpy 1.19.1 py38hbc911f0_0
        - numpy-base 1.19.1 py38hfa32c7d_0
        - openssl 1.1.1h h7b6447c_0
        - pandas 1.1.3 py38he6710b0_0
        - patsy 0.5.1 py38_0
        - pip 20.2.3 py38_0
        - python 3.8.5 h7579374_1
        - python-dateutil 2.8.1 py_0
        - pytz 2020.1 py_0
        - readline 8.0 h7b6447c_0
        - scipy 1.5.2 py38h0b6359f_0
        - setuptools 50.3.0 py38hb0f4dca_1
        - six 1.15.0 py_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - numpy >=1.19.1,<2.0a0
        - pandas >=0.21
        - patsy >=0.5.1
        - python >=3.8,<3.9.0a0
        - scipy >=1.0
test:
    commands:
        - pip check
    imports:
        - statsmodels
    requires:
        - pip
about:
    description: 'Statsmodels is a Python module that allows users to explore data,
        estimate

        statistical models, and perform statistical tests. An extensive list of

        descriptive statistics, statistical tests, plotting functions, and result

        statistics are available for different types of data and each estimator.

        Researchers across fields may find that statsmodels fully meets their

        needs for statistical computing and data analysis in Python.

        '
    dev_url: https://github.com/statsmodels/statsmodels
    doc_source_url: https://github.com/statsmodels/statsmodels/blob/master/docs/source/index.rst
    doc_url: https://www.statsmodels.org/stable/
    home: https://www.statsmodels.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: INSTALL.txt
    summary: Statistical computations and models for use with SciPy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - croth1
        - ocefpaf
        - tomaugspurger
