# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/jupyter-1.0.0-python_3.8-on-linux_64, last modified Wed Aug  7 19:26:20 2019
# ------------------------------------------------

package:
    name: jupyter
    version: 1.0.0
source:
    fn: jupyter-1.0.0.tar.gz
    sha256: d9dc4b3318f310e34c82951ea5d6683f67bed7def4b259fafbfe4f1beb1d8e5f
    url: https://pypi.python.org/packages/source/j/jupyter/jupyter-1.0.0.tar.gz
build:
    number: '7'
    string: py38_7
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py38_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - pip 20.0.2 py38_0
        - python 3.8.1 h0371630_1
        - readline 7.0 h7b6447c_5
        - setuptools 45.1.0 py38_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - ipykernel
        - ipywidgets
        - jupyter_console
        - nbconvert
        - notebook
        - python >=3.8,<3.9.0a0
        - qtconsole
test:
    commands:
        - jupyter --help
about:
    description: 'Jupyter Notebook is a web application, a browser-based tool for
        interactive authoring of documents

        which combine explanatory text, mathematics, computations and their rich media
        output.

        '
    dev_url: https://github.com/jupyter/jupyter
    doc_source_url: https://github.com/jupyter/notebook/blob/master/docs/source/index.rst
    doc_url: http://jupyter.readthedocs.org/
    home: http://jupyter.org
    license: BSD 3-Clause
    license_file: LICENSE
    summary: Jupyter metapackage. Install all the Jupyter components in one go.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
