# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# C:\ci\containers\000011kkcs4\tmp\build\80754af9\aggregate\itsdangerous-feedstock\recipe, last modified Wed Oct 30 05:34:06 2019
# ------------------------------------------------

package:
    name: itsdangerous
    version: 1.1.0
source:
    fn: itsdangerous-1.1.0.tar.gz
    sha256: 321b033d07f2a4136d3ec762eac9f16a10ccd60f53c0c91af90217ace7ba1f19
    url: https://pypi.io/packages/source/i/itsdangerous/itsdangerous-1.1.0.tar.gz
build:
    noarch: python
    number: '0'
    script: C:\\ci\\itsdangerous_1572439184986\\_h_env\\python.exe -m pip install
        . -vvv
    string: py_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - openssl 1.1.1d he774522_3
        - pip 19.3.1 py38_0
        - python 3.8.0 hff0d562_0
        - setuptools 41.4.0 py38_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - wheel 0.33.6 py38_0
        - wincertstore 0.2 py38_0
    run:
        - python
test:
    imports:
        - itsdangerous
about:
    description: 'Internally itsdangerous uses HMAC and SHA1 for signing data and
        bases the

        implementation on the Django signing module.  It also however supports JSON
        Web

        Signatures (JWS).

        '
    dev_url: https://github.com/pallets/itsdangerous
    doc_source_url: https://github.com/pallets/itsdangerous/blob/master/docs/index.rst
    doc_url: http://pythonhosted.org/itsdangerous
    home: https://github.com/pallets/itsdangerous
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.rst
    summary: Various helpers to pass trusted data to untrusted environments.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - nicoddemus
        - williamjamir
